name = "down-under-chauffeur"
compatibility_date = "2025-04-03"

[assets]
not_found_handling = "single-page-application"

[vars]
NODE_ENV = "production"
VITE_SERVER_URL = "https://down-under-chauffeur-server.davannarts.workers.dev"
VITE_CLIENT_URL = "https://down-under-chauffeur.davannarts.workers.dev"

