-- Template package for hourly bookings priced from vehicle pricing config (instant quote / book-service).
INSERT OR IGNORE INTO package_service_types (id, name, description, icon, rate_type, is_active, display_order, created_at, updated_at)
VALUES (
	'sys_hourly_iq_svc_type',
	'__system_hourly_instant_quote',
	'Internal hourly service type for vehicle-priced hourly bookings.',
	NULL,
	'hourly',
	1,
	9999,
	unixepoch(),
	unixepoch()
);

INSERT OR IGNORE INTO packages (
	id,
	name,
	description,
	category_id,
	service_type_id,
	banner_image_url,
	duration,
	max_distance,
	fixed_price,
	hourly_rate,
	extra_km_price,
	extra_hour_price,
	deposit_required,
	max_passengers,
	advance_booking_hours,
	cancellation_hours,
	includes_driver,
	includes_fuel,
	includes_tolls,
	includes_waiting,
	waiting_time_minutes,
	is_available,
	is_published,
	available_days,
	available_time_start,
	available_time_end,
	created_at,
	updated_at
) VALUES (
	'sys_hourly_iq_template',
	'Hourly vehicle booking',
	'Template for hourly bookings; rates come from vehicle pricing when a vehicle is selected.',
	NULL,
	'sys_hourly_iq_svc_type',
	NULL,
	NULL,
	NULL,
	NULL,
	0.01,
	NULL,
	NULL,
	NULL,
	20,
	24,
	24,
	1,
	1,
	0,
	0,
	0,
	1,
	0,
	NULL,
	NULL,
	NULL,
	unixepoch(),
	unixepoch()
);
