name = "down-under-chauffeur-server"
main = "src/index.ts"
compatibility_date = "2025-06-15"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://down-under-chauffeur.davannarts.workers.dev"
BETTER_AUTH_SECRET="sdNWG3346gApFEayd0QfPFsEjTLcibq2"
BETTER_AUTH_URL="https://down-under-chauffeur-server.davannarts.workers.dev"
GOOGLE_CLIENT_ID = "REDACTED_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "REDACTED_GOOGLE_CLIENT_SECRET"

[[d1_databases]]
binding = "DB"
database_name = "down-under-chauffeur-test-db"
database_id = "8682a4c3-fcc3-4435-9a31-1b710dd1a673"
migrations_dir = "./src/db/migrations"


