/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MyBookingsLayoutRouteImport } from './routes/my-bookings/_layout'
import { Route as DriverLayoutRouteImport } from './routes/driver/_layout'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as MarketingTermsAndConditionsRouteImport } from './routes/_marketing/terms-and-conditions'
import { Route as MarketingServicesRouteImport } from './routes/_marketing/services'
import { Route as MarketingSelectVehicleRouteImport } from './routes/_marketing/select-vehicle'
import { Route as MarketingQuoteResultsRouteImport } from './routes/_marketing/quote-results'
import { Route as MarketingProfileRouteImport } from './routes/_marketing/profile'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingFleetRouteImport } from './routes/_marketing/fleet'
import { Route as MarketingFaqsRouteImport } from './routes/_marketing/faqs'
import { Route as MarketingDashboardRouteImport } from './routes/_marketing/dashboard'
import { Route as MarketingContactUsRouteImport } from './routes/_marketing/contact-us'
import { Route as MarketingCalculateQuoteRouteImport } from './routes/_marketing/calculate-quote'
import { Route as MarketingAboutUsRouteImport } from './routes/_marketing/about-us'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as MyBookingsLayoutIndexRouteImport } from './routes/my-bookings/_layout/index'
import { Route as DriverLayoutIndexRouteImport } from './routes/driver/_layout/index'
import { Route as MyBookingsLayoutTripsRouteImport } from './routes/my-bookings/_layout/trips'
import { Route as MyBookingsLayoutHistoryRouteImport } from './routes/my-bookings/_layout/history'
import { Route as MyBookingsLayoutDashboardRouteImport } from './routes/my-bookings/_layout/dashboard'
import { Route as DriverLayoutTripsRouteImport } from './routes/driver/_layout/trips'
import { Route as DriverLayoutSettingsRouteImport } from './routes/driver/_layout/settings'
import { Route as DriverLayoutProfileRouteImport } from './routes/driver/_layout/profile'
import { Route as DriverLayoutOnboardingRouteImport } from './routes/driver/_layout/onboarding'
import { Route as DriverLayoutHistoryRouteImport } from './routes/driver/_layout/history'
import { Route as DriverLayoutDashboardRouteImport } from './routes/driver/_layout/dashboard'
import { Route as DriverLayoutAvailableRouteImport } from './routes/driver/_layout/available'
import { Route as DashboardLayoutServicesRouteImport } from './routes/dashboard/_layout/services'
import { Route as DashboardLayoutQuoteResultsRouteImport } from './routes/dashboard/_layout/quote-results'
import { Route as DashboardLayoutInstantQuoteRouteImport } from './routes/dashboard/_layout/instant-quote'
import { Route as DashboardLayoutCarsRouteImport } from './routes/dashboard/_layout/cars'
import { Route as DashboardLayoutCalculateQuoteRouteImport } from './routes/dashboard/_layout/calculate-quote'
import { Route as DashboardLayoutBookAppointmentRouteImport } from './routes/dashboard/_layout/book-appointment'
import { Route as AdminDashboardLayoutRouteImport } from './routes/admin/dashboard/_layout'
import { Route as MarketingBookServiceServiceIdRouteImport } from './routes/_marketing/book-service.$serviceId'
import { Route as MarketingBookQuoteQuoteIdRouteImport } from './routes/_marketing/book-quote.$quoteId'
import { Route as MarketingBookCarCarIdRouteImport } from './routes/_marketing/book-car.$carId'
import { Route as MarketingAccountSettingsRouteImport } from './routes/_marketing/account/settings'
import { Route as AdminDashboardLayoutIndexRouteImport } from './routes/admin/dashboard/_layout/index'
import { Route as DashboardLayoutCarDetailsCarIdRouteImport } from './routes/dashboard/_layout/car-details.$carId'
import { Route as DashboardLayoutBookServiceServiceIdRouteImport } from './routes/dashboard/_layout/book-service/$serviceId'
import { Route as DashboardLayoutBookAppointmentCarIdRouteImport } from './routes/dashboard/_layout/book-appointment.$carId'
import { Route as AdminDashboardLayoutSettingsRouteImport } from './routes/admin/dashboard/_layout/settings'
import { Route as AdminDashboardLayoutTodaysScheduledIndexRouteImport } from './routes/admin/dashboard/_layout/todays-scheduled/index'
import { Route as AdminDashboardLayoutSettingsIndexRouteImport } from './routes/admin/dashboard/_layout/settings/index'
import { Route as AdminDashboardLayoutReportIndexRouteImport } from './routes/admin/dashboard/_layout/report/index'
import { Route as AdminDashboardLayoutPublishedIndexRouteImport } from './routes/admin/dashboard/_layout/published/index'
import { Route as AdminDashboardLayoutPublicationsIndexRouteImport } from './routes/admin/dashboard/_layout/publications/index'
import { Route as AdminDashboardLayoutPricingConfigIndexRouteImport } from './routes/admin/dashboard/_layout/pricing-config/index'
import { Route as AdminDashboardLayoutPackagesIndexRouteImport } from './routes/admin/dashboard/_layout/packages/index'
import { Route as AdminDashboardLayoutInvoicesIndexRouteImport } from './routes/admin/dashboard/_layout/invoices/index'
import { Route as AdminDashboardLayoutInboxIndexRouteImport } from './routes/admin/dashboard/_layout/inbox/index'
import { Route as AdminDashboardLayoutDriversIndexRouteImport } from './routes/admin/dashboard/_layout/drivers/index'
import { Route as AdminDashboardLayoutCarsIndexRouteImport } from './routes/admin/dashboard/_layout/cars/index'
import { Route as AdminDashboardLayoutBookmarksIndexRouteImport } from './routes/admin/dashboard/_layout/bookmarks/index'
import { Route as AdminDashboardLayoutBookingsIndexRouteImport } from './routes/admin/dashboard/_layout/bookings/index'
import { Route as AdminDashboardLayoutBoardIndexRouteImport } from './routes/admin/dashboard/_layout/board/index'
import { Route as AdminDashboardLayoutAnalyticsIndexRouteImport } from './routes/admin/dashboard/_layout/analytics/index'
import { Route as AdminDashboardLayoutAdminTestingIndexRouteImport } from './routes/admin/dashboard/_layout/admin-testing/index'
import { Route as AdminDashboardLayoutSettingsSecurityRouteImport } from './routes/admin/dashboard/_layout/settings/security'
import { Route as AdminDashboardLayoutSettingsAccountRouteImport } from './routes/admin/dashboard/_layout/settings/account'
import { Route as AdminDashboardLayoutDriversOnboardingRouteImport } from './routes/admin/dashboard/_layout/drivers/onboarding'
import { Route as AdminDashboardLayoutCarsAddCarRouteImport } from './routes/admin/dashboard/_layout/cars/add-car'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MyBookingsLayoutRoute = MyBookingsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => MyBookingsRoute,
} as any)
const DriverLayoutRoute = DriverLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DriverRoute,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingTermsAndConditionsRoute =
  MarketingTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingServicesRoute = MarketingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSelectVehicleRoute = MarketingSelectVehicleRouteImport.update({
  id: '/select-vehicle',
  path: '/select-vehicle',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingQuoteResultsRoute = MarketingQuoteResultsRouteImport.update({
  id: '/quote-results',
  path: '/quote-results',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProfileRoute = MarketingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFleetRoute = MarketingFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqsRoute = MarketingFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDashboardRoute = MarketingDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactUsRoute = MarketingContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCalculateQuoteRoute = MarketingCalculateQuoteRouteImport.update({
  id: '/calculate-quote',
  path: '/calculate-quote',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutUsRoute = MarketingAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const MyBookingsLayoutIndexRoute = MyBookingsLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyBookingsLayoutRoute,
} as any)
const DriverLayoutIndexRoute = DriverLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const MyBookingsLayoutTripsRoute = MyBookingsLayoutTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => MyBookingsLayoutRoute,
} as any)
const MyBookingsLayoutHistoryRoute = MyBookingsLayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MyBookingsLayoutRoute,
} as any)
const MyBookingsLayoutDashboardRoute =
  MyBookingsLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => MyBookingsLayoutRoute,
  } as any)
const DriverLayoutTripsRoute = DriverLayoutTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutSettingsRoute = DriverLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutProfileRoute = DriverLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutOnboardingRoute = DriverLayoutOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutHistoryRoute = DriverLayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutDashboardRoute = DriverLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutAvailableRoute = DriverLayoutAvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DashboardLayoutServicesRoute = DashboardLayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutQuoteResultsRoute =
  DashboardLayoutQuoteResultsRouteImport.update({
    id: '/quote-results',
    path: '/quote-results',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInstantQuoteRoute =
  DashboardLayoutInstantQuoteRouteImport.update({
    id: '/instant-quote',
    path: '/instant-quote',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCarsRoute = DashboardLayoutCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutCalculateQuoteRoute =
  DashboardLayoutCalculateQuoteRouteImport.update({
    id: '/calculate-quote',
    path: '/calculate-quote',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBookAppointmentRoute =
  DashboardLayoutBookAppointmentRouteImport.update({
    id: '/book-appointment',
    path: '/book-appointment',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutRoute = AdminDashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const MarketingBookServiceServiceIdRoute =
  MarketingBookServiceServiceIdRouteImport.update({
    id: '/book-service/$serviceId',
    path: '/book-service/$serviceId',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingBookQuoteQuoteIdRoute =
  MarketingBookQuoteQuoteIdRouteImport.update({
    id: '/book-quote/$quoteId',
    path: '/book-quote/$quoteId',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingBookCarCarIdRoute = MarketingBookCarCarIdRouteImport.update({
  id: '/book-car/$carId',
  path: '/book-car/$carId',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAccountSettingsRoute =
  MarketingAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => MarketingRoute,
  } as any)
const AdminDashboardLayoutIndexRoute =
  AdminDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const DashboardLayoutCarDetailsCarIdRoute =
  DashboardLayoutCarDetailsCarIdRouteImport.update({
    id: '/car-details/$carId',
    path: '/car-details/$carId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBookServiceServiceIdRoute =
  DashboardLayoutBookServiceServiceIdRouteImport.update({
    id: '/book-service/$serviceId',
    path: '/book-service/$serviceId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBookAppointmentCarIdRoute =
  DashboardLayoutBookAppointmentCarIdRouteImport.update({
    id: '/$carId',
    path: '/$carId',
    getParentRoute: () => DashboardLayoutBookAppointmentRoute,
  } as any)
const AdminDashboardLayoutSettingsRoute =
  AdminDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutTodaysScheduledIndexRoute =
  AdminDashboardLayoutTodaysScheduledIndexRouteImport.update({
    id: '/todays-scheduled/',
    path: '/todays-scheduled/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutSettingsIndexRoute =
  AdminDashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardLayoutSettingsRoute,
  } as any)
const AdminDashboardLayoutReportIndexRoute =
  AdminDashboardLayoutReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutPublishedIndexRoute =
  AdminDashboardLayoutPublishedIndexRouteImport.update({
    id: '/published/',
    path: '/published/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutPublicationsIndexRoute =
  AdminDashboardLayoutPublicationsIndexRouteImport.update({
    id: '/publications/',
    path: '/publications/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutPricingConfigIndexRoute =
  AdminDashboardLayoutPricingConfigIndexRouteImport.update({
    id: '/pricing-config/',
    path: '/pricing-config/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutPackagesIndexRoute =
  AdminDashboardLayoutPackagesIndexRouteImport.update({
    id: '/packages/',
    path: '/packages/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutInvoicesIndexRoute =
  AdminDashboardLayoutInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutInboxIndexRoute =
  AdminDashboardLayoutInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDriversIndexRoute =
  AdminDashboardLayoutDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutCarsIndexRoute =
  AdminDashboardLayoutCarsIndexRouteImport.update({
    id: '/cars/',
    path: '/cars/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutBookmarksIndexRoute =
  AdminDashboardLayoutBookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutBookingsIndexRoute =
  AdminDashboardLayoutBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutBoardIndexRoute =
  AdminDashboardLayoutBoardIndexRouteImport.update({
    id: '/board/',
    path: '/board/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutAnalyticsIndexRoute =
  AdminDashboardLayoutAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutAdminTestingIndexRoute =
  AdminDashboardLayoutAdminTestingIndexRouteImport.update({
    id: '/admin-testing/',
    path: '/admin-testing/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutSettingsSecurityRoute =
  AdminDashboardLayoutSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AdminDashboardLayoutSettingsRoute,
  } as any)
const AdminDashboardLayoutSettingsAccountRoute =
  AdminDashboardLayoutSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AdminDashboardLayoutSettingsRoute,
  } as any)
const AdminDashboardLayoutDriversOnboardingRoute =
  AdminDashboardLayoutDriversOnboardingRouteImport.update({
    id: '/drivers/onboarding',
    path: '/drivers/onboarding',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutCarsAddCarRoute =
  AdminDashboardLayoutCarsAddCarRouteImport.update({
    id: '/cars/add-car',
    path: '/cars/add-car',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about-us': typeof MarketingAboutUsRoute
  '/calculate-quote': typeof MarketingCalculateQuoteRoute
  '/contact-us': typeof MarketingContactUsRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/faqs': typeof MarketingFaqsRoute
  '/fleet': typeof MarketingFleetRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/profile': typeof MarketingProfileRoute
  '/quote-results': typeof MarketingQuoteResultsRoute
  '/select-vehicle': typeof MarketingSelectVehicleRoute
  '/services': typeof MarketingServicesRoute
  '/terms-and-conditions': typeof MarketingTermsAndConditionsRoute
  '/driver': typeof DriverLayoutRouteWithChildren
  '/my-bookings': typeof MyBookingsLayoutRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/account/settings': typeof MarketingAccountSettingsRoute
  '/book-car/$carId': typeof MarketingBookCarCarIdRoute
  '/book-quote/$quoteId': typeof MarketingBookQuoteQuoteIdRoute
  '/book-service/$serviceId': typeof MarketingBookServiceServiceIdRoute
  '/admin/dashboard': typeof AdminDashboardLayoutRouteWithChildren
  '/dashboard/book-appointment': typeof DashboardLayoutBookAppointmentRouteWithChildren
  '/dashboard/calculate-quote': typeof DashboardLayoutCalculateQuoteRoute
  '/dashboard/cars': typeof DashboardLayoutCarsRoute
  '/dashboard/instant-quote': typeof DashboardLayoutInstantQuoteRoute
  '/dashboard/quote-results': typeof DashboardLayoutQuoteResultsRoute
  '/dashboard/services': typeof DashboardLayoutServicesRoute
  '/driver/available': typeof DriverLayoutAvailableRoute
  '/driver/dashboard': typeof DriverLayoutDashboardRoute
  '/driver/history': typeof DriverLayoutHistoryRoute
  '/driver/onboarding': typeof DriverLayoutOnboardingRoute
  '/driver/profile': typeof DriverLayoutProfileRoute
  '/driver/settings': typeof DriverLayoutSettingsRoute
  '/driver/trips': typeof DriverLayoutTripsRoute
  '/my-bookings/dashboard': typeof MyBookingsLayoutDashboardRoute
  '/my-bookings/history': typeof MyBookingsLayoutHistoryRoute
  '/my-bookings/trips': typeof MyBookingsLayoutTripsRoute
  '/driver/': typeof DriverLayoutIndexRoute
  '/my-bookings/': typeof MyBookingsLayoutIndexRoute
  '/admin/dashboard/settings': typeof AdminDashboardLayoutSettingsRouteWithChildren
  '/dashboard/book-appointment/$carId': typeof DashboardLayoutBookAppointmentCarIdRoute
  '/dashboard/book-service/$serviceId': typeof DashboardLayoutBookServiceServiceIdRoute
  '/dashboard/car-details/$carId': typeof DashboardLayoutCarDetailsCarIdRoute
  '/admin/dashboard/': typeof AdminDashboardLayoutIndexRoute
  '/admin/dashboard/cars/add-car': typeof AdminDashboardLayoutCarsAddCarRoute
  '/admin/dashboard/drivers/onboarding': typeof AdminDashboardLayoutDriversOnboardingRoute
  '/admin/dashboard/settings/account': typeof AdminDashboardLayoutSettingsAccountRoute
  '/admin/dashboard/settings/security': typeof AdminDashboardLayoutSettingsSecurityRoute
  '/admin/dashboard/admin-testing': typeof AdminDashboardLayoutAdminTestingIndexRoute
  '/admin/dashboard/analytics': typeof AdminDashboardLayoutAnalyticsIndexRoute
  '/admin/dashboard/board': typeof AdminDashboardLayoutBoardIndexRoute
  '/admin/dashboard/bookings': typeof AdminDashboardLayoutBookingsIndexRoute
  '/admin/dashboard/bookmarks': typeof AdminDashboardLayoutBookmarksIndexRoute
  '/admin/dashboard/cars': typeof AdminDashboardLayoutCarsIndexRoute
  '/admin/dashboard/drivers': typeof AdminDashboardLayoutDriversIndexRoute
  '/admin/dashboard/inbox': typeof AdminDashboardLayoutInboxIndexRoute
  '/admin/dashboard/invoices': typeof AdminDashboardLayoutInvoicesIndexRoute
  '/admin/dashboard/packages': typeof AdminDashboardLayoutPackagesIndexRoute
  '/admin/dashboard/pricing-config': typeof AdminDashboardLayoutPricingConfigIndexRoute
  '/admin/dashboard/publications': typeof AdminDashboardLayoutPublicationsIndexRoute
  '/admin/dashboard/published': typeof AdminDashboardLayoutPublishedIndexRoute
  '/admin/dashboard/report': typeof AdminDashboardLayoutReportIndexRoute
  '/admin/dashboard/settings/': typeof AdminDashboardLayoutSettingsIndexRoute
  '/admin/dashboard/todays-scheduled': typeof AdminDashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about-us': typeof MarketingAboutUsRoute
  '/calculate-quote': typeof MarketingCalculateQuoteRoute
  '/contact-us': typeof MarketingContactUsRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/faqs': typeof MarketingFaqsRoute
  '/fleet': typeof MarketingFleetRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/profile': typeof MarketingProfileRoute
  '/quote-results': typeof MarketingQuoteResultsRoute
  '/select-vehicle': typeof MarketingSelectVehicleRoute
  '/services': typeof MarketingServicesRoute
  '/terms-and-conditions': typeof MarketingTermsAndConditionsRoute
  '/': typeof MarketingIndexRoute
  '/account/settings': typeof MarketingAccountSettingsRoute
  '/book-car/$carId': typeof MarketingBookCarCarIdRoute
  '/book-quote/$quoteId': typeof MarketingBookQuoteQuoteIdRoute
  '/book-service/$serviceId': typeof MarketingBookServiceServiceIdRoute
  '/dashboard/book-appointment': typeof DashboardLayoutBookAppointmentRouteWithChildren
  '/dashboard/calculate-quote': typeof DashboardLayoutCalculateQuoteRoute
  '/dashboard/cars': typeof DashboardLayoutCarsRoute
  '/dashboard/instant-quote': typeof DashboardLayoutInstantQuoteRoute
  '/dashboard/quote-results': typeof DashboardLayoutQuoteResultsRoute
  '/dashboard/services': typeof DashboardLayoutServicesRoute
  '/driver/available': typeof DriverLayoutAvailableRoute
  '/driver/dashboard': typeof DriverLayoutDashboardRoute
  '/driver/history': typeof DriverLayoutHistoryRoute
  '/driver/onboarding': typeof DriverLayoutOnboardingRoute
  '/driver/profile': typeof DriverLayoutProfileRoute
  '/driver/settings': typeof DriverLayoutSettingsRoute
  '/driver/trips': typeof DriverLayoutTripsRoute
  '/my-bookings/dashboard': typeof MyBookingsLayoutDashboardRoute
  '/my-bookings/history': typeof MyBookingsLayoutHistoryRoute
  '/my-bookings/trips': typeof MyBookingsLayoutTripsRoute
  '/driver': typeof DriverLayoutIndexRoute
  '/my-bookings': typeof MyBookingsLayoutIndexRoute
  '/dashboard/book-appointment/$carId': typeof DashboardLayoutBookAppointmentCarIdRoute
  '/dashboard/book-service/$serviceId': typeof DashboardLayoutBookServiceServiceIdRoute
  '/dashboard/car-details/$carId': typeof DashboardLayoutCarDetailsCarIdRoute
  '/admin/dashboard': typeof AdminDashboardLayoutIndexRoute
  '/admin/dashboard/cars/add-car': typeof AdminDashboardLayoutCarsAddCarRoute
  '/admin/dashboard/drivers/onboarding': typeof AdminDashboardLayoutDriversOnboardingRoute
  '/admin/dashboard/settings/account': typeof AdminDashboardLayoutSettingsAccountRoute
  '/admin/dashboard/settings/security': typeof AdminDashboardLayoutSettingsSecurityRoute
  '/admin/dashboard/admin-testing': typeof AdminDashboardLayoutAdminTestingIndexRoute
  '/admin/dashboard/analytics': typeof AdminDashboardLayoutAnalyticsIndexRoute
  '/admin/dashboard/board': typeof AdminDashboardLayoutBoardIndexRoute
  '/admin/dashboard/bookings': typeof AdminDashboardLayoutBookingsIndexRoute
  '/admin/dashboard/bookmarks': typeof AdminDashboardLayoutBookmarksIndexRoute
  '/admin/dashboard/cars': typeof AdminDashboardLayoutCarsIndexRoute
  '/admin/dashboard/drivers': typeof AdminDashboardLayoutDriversIndexRoute
  '/admin/dashboard/inbox': typeof AdminDashboardLayoutInboxIndexRoute
  '/admin/dashboard/invoices': typeof AdminDashboardLayoutInvoicesIndexRoute
  '/admin/dashboard/packages': typeof AdminDashboardLayoutPackagesIndexRoute
  '/admin/dashboard/pricing-config': typeof AdminDashboardLayoutPricingConfigIndexRoute
  '/admin/dashboard/publications': typeof AdminDashboardLayoutPublicationsIndexRoute
  '/admin/dashboard/published': typeof AdminDashboardLayoutPublishedIndexRoute
  '/admin/dashboard/report': typeof AdminDashboardLayoutReportIndexRoute
  '/admin/dashboard/settings': typeof AdminDashboardLayoutSettingsIndexRoute
  '/admin/dashboard/todays-scheduled': typeof AdminDashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_marketing/about-us': typeof MarketingAboutUsRoute
  '/_marketing/calculate-quote': typeof MarketingCalculateQuoteRoute
  '/_marketing/contact-us': typeof MarketingContactUsRoute
  '/_marketing/dashboard': typeof MarketingDashboardRoute
  '/_marketing/faqs': typeof MarketingFaqsRoute
  '/_marketing/fleet': typeof MarketingFleetRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/profile': typeof MarketingProfileRoute
  '/_marketing/quote-results': typeof MarketingQuoteResultsRoute
  '/_marketing/select-vehicle': typeof MarketingSelectVehicleRoute
  '/_marketing/services': typeof MarketingServicesRoute
  '/_marketing/terms-and-conditions': typeof MarketingTermsAndConditionsRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/driver/_layout': typeof DriverLayoutRouteWithChildren
  '/my-bookings/_layout': typeof MyBookingsLayoutRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/account/settings': typeof MarketingAccountSettingsRoute
  '/_marketing/book-car/$carId': typeof MarketingBookCarCarIdRoute
  '/_marketing/book-quote/$quoteId': typeof MarketingBookQuoteQuoteIdRoute
  '/_marketing/book-service/$serviceId': typeof MarketingBookServiceServiceIdRoute
  '/admin/dashboard/_layout': typeof AdminDashboardLayoutRouteWithChildren
  '/dashboard/_layout/book-appointment': typeof DashboardLayoutBookAppointmentRouteWithChildren
  '/dashboard/_layout/calculate-quote': typeof DashboardLayoutCalculateQuoteRoute
  '/dashboard/_layout/cars': typeof DashboardLayoutCarsRoute
  '/dashboard/_layout/instant-quote': typeof DashboardLayoutInstantQuoteRoute
  '/dashboard/_layout/quote-results': typeof DashboardLayoutQuoteResultsRoute
  '/dashboard/_layout/services': typeof DashboardLayoutServicesRoute
  '/driver/_layout/available': typeof DriverLayoutAvailableRoute
  '/driver/_layout/dashboard': typeof DriverLayoutDashboardRoute
  '/driver/_layout/history': typeof DriverLayoutHistoryRoute
  '/driver/_layout/onboarding': typeof DriverLayoutOnboardingRoute
  '/driver/_layout/profile': typeof DriverLayoutProfileRoute
  '/driver/_layout/settings': typeof DriverLayoutSettingsRoute
  '/driver/_layout/trips': typeof DriverLayoutTripsRoute
  '/my-bookings/_layout/dashboard': typeof MyBookingsLayoutDashboardRoute
  '/my-bookings/_layout/history': typeof MyBookingsLayoutHistoryRoute
  '/my-bookings/_layout/trips': typeof MyBookingsLayoutTripsRoute
  '/driver/_layout/': typeof DriverLayoutIndexRoute
  '/my-bookings/_layout/': typeof MyBookingsLayoutIndexRoute
  '/admin/dashboard/_layout/settings': typeof AdminDashboardLayoutSettingsRouteWithChildren
  '/dashboard/_layout/book-appointment/$carId': typeof DashboardLayoutBookAppointmentCarIdRoute
  '/dashboard/_layout/book-service/$serviceId': typeof DashboardLayoutBookServiceServiceIdRoute
  '/dashboard/_layout/car-details/$carId': typeof DashboardLayoutCarDetailsCarIdRoute
  '/admin/dashboard/_layout/': typeof AdminDashboardLayoutIndexRoute
  '/admin/dashboard/_layout/cars/add-car': typeof AdminDashboardLayoutCarsAddCarRoute
  '/admin/dashboard/_layout/drivers/onboarding': typeof AdminDashboardLayoutDriversOnboardingRoute
  '/admin/dashboard/_layout/settings/account': typeof AdminDashboardLayoutSettingsAccountRoute
  '/admin/dashboard/_layout/settings/security': typeof AdminDashboardLayoutSettingsSecurityRoute
  '/admin/dashboard/_layout/admin-testing/': typeof AdminDashboardLayoutAdminTestingIndexRoute
  '/admin/dashboard/_layout/analytics/': typeof AdminDashboardLayoutAnalyticsIndexRoute
  '/admin/dashboard/_layout/board/': typeof AdminDashboardLayoutBoardIndexRoute
  '/admin/dashboard/_layout/bookings/': typeof AdminDashboardLayoutBookingsIndexRoute
  '/admin/dashboard/_layout/bookmarks/': typeof AdminDashboardLayoutBookmarksIndexRoute
  '/admin/dashboard/_layout/cars/': typeof AdminDashboardLayoutCarsIndexRoute
  '/admin/dashboard/_layout/drivers/': typeof AdminDashboardLayoutDriversIndexRoute
  '/admin/dashboard/_layout/inbox/': typeof AdminDashboardLayoutInboxIndexRoute
  '/admin/dashboard/_layout/invoices/': typeof AdminDashboardLayoutInvoicesIndexRoute
  '/admin/dashboard/_layout/packages/': typeof AdminDashboardLayoutPackagesIndexRoute
  '/admin/dashboard/_layout/pricing-config/': typeof AdminDashboardLayoutPricingConfigIndexRoute
  '/admin/dashboard/_layout/publications/': typeof AdminDashboardLayoutPublicationsIndexRoute
  '/admin/dashboard/_layout/published/': typeof AdminDashboardLayoutPublishedIndexRoute
  '/admin/dashboard/_layout/report/': typeof AdminDashboardLayoutReportIndexRoute
  '/admin/dashboard/_layout/settings/': typeof AdminDashboardLayoutSettingsIndexRoute
  '/admin/dashboard/_layout/todays-scheduled/': typeof AdminDashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/about-us'
    | '/calculate-quote'
    | '/contact-us'
    | '/dashboard'
    | '/faqs'
    | '/fleet'
    | '/privacy'
    | '/profile'
    | '/quote-results'
    | '/select-vehicle'
    | '/services'
    | '/terms-and-conditions'
    | '/driver'
    | '/my-bookings'
    | '/'
    | '/account/settings'
    | '/book-car/$carId'
    | '/book-quote/$quoteId'
    | '/book-service/$serviceId'
    | '/admin/dashboard'
    | '/dashboard/book-appointment'
    | '/dashboard/calculate-quote'
    | '/dashboard/cars'
    | '/dashboard/instant-quote'
    | '/dashboard/quote-results'
    | '/dashboard/services'
    | '/driver/available'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/settings'
    | '/driver/trips'
    | '/my-bookings/dashboard'
    | '/my-bookings/history'
    | '/my-bookings/trips'
    | '/driver/'
    | '/my-bookings/'
    | '/admin/dashboard/settings'
    | '/dashboard/book-appointment/$carId'
    | '/dashboard/book-service/$serviceId'
    | '/dashboard/car-details/$carId'
    | '/admin/dashboard/'
    | '/admin/dashboard/cars/add-car'
    | '/admin/dashboard/drivers/onboarding'
    | '/admin/dashboard/settings/account'
    | '/admin/dashboard/settings/security'
    | '/admin/dashboard/admin-testing'
    | '/admin/dashboard/analytics'
    | '/admin/dashboard/board'
    | '/admin/dashboard/bookings'
    | '/admin/dashboard/bookmarks'
    | '/admin/dashboard/cars'
    | '/admin/dashboard/drivers'
    | '/admin/dashboard/inbox'
    | '/admin/dashboard/invoices'
    | '/admin/dashboard/packages'
    | '/admin/dashboard/pricing-config'
    | '/admin/dashboard/publications'
    | '/admin/dashboard/published'
    | '/admin/dashboard/report'
    | '/admin/dashboard/settings/'
    | '/admin/dashboard/todays-scheduled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/about-us'
    | '/calculate-quote'
    | '/contact-us'
    | '/dashboard'
    | '/faqs'
    | '/fleet'
    | '/privacy'
    | '/profile'
    | '/quote-results'
    | '/select-vehicle'
    | '/services'
    | '/terms-and-conditions'
    | '/'
    | '/account/settings'
    | '/book-car/$carId'
    | '/book-quote/$quoteId'
    | '/book-service/$serviceId'
    | '/dashboard/book-appointment'
    | '/dashboard/calculate-quote'
    | '/dashboard/cars'
    | '/dashboard/instant-quote'
    | '/dashboard/quote-results'
    | '/dashboard/services'
    | '/driver/available'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/settings'
    | '/driver/trips'
    | '/my-bookings/dashboard'
    | '/my-bookings/history'
    | '/my-bookings/trips'
    | '/driver'
    | '/my-bookings'
    | '/dashboard/book-appointment/$carId'
    | '/dashboard/book-service/$serviceId'
    | '/dashboard/car-details/$carId'
    | '/admin/dashboard'
    | '/admin/dashboard/cars/add-car'
    | '/admin/dashboard/drivers/onboarding'
    | '/admin/dashboard/settings/account'
    | '/admin/dashboard/settings/security'
    | '/admin/dashboard/admin-testing'
    | '/admin/dashboard/analytics'
    | '/admin/dashboard/board'
    | '/admin/dashboard/bookings'
    | '/admin/dashboard/bookmarks'
    | '/admin/dashboard/cars'
    | '/admin/dashboard/drivers'
    | '/admin/dashboard/inbox'
    | '/admin/dashboard/invoices'
    | '/admin/dashboard/packages'
    | '/admin/dashboard/pricing-config'
    | '/admin/dashboard/publications'
    | '/admin/dashboard/published'
    | '/admin/dashboard/report'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/todays-scheduled'
  id:
    | '__root__'
    | '/_auth'
    | '/_marketing'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_marketing/about-us'
    | '/_marketing/calculate-quote'
    | '/_marketing/contact-us'
    | '/_marketing/dashboard'
    | '/_marketing/faqs'
    | '/_marketing/fleet'
    | '/_marketing/privacy'
    | '/_marketing/profile'
    | '/_marketing/quote-results'
    | '/_marketing/select-vehicle'
    | '/_marketing/services'
    | '/_marketing/terms-and-conditions'
    | '/dashboard/_layout'
    | '/driver/_layout'
    | '/my-bookings/_layout'
    | '/_marketing/'
    | '/_marketing/account/settings'
    | '/_marketing/book-car/$carId'
    | '/_marketing/book-quote/$quoteId'
    | '/_marketing/book-service/$serviceId'
    | '/admin/dashboard/_layout'
    | '/dashboard/_layout/book-appointment'
    | '/dashboard/_layout/calculate-quote'
    | '/dashboard/_layout/cars'
    | '/dashboard/_layout/instant-quote'
    | '/dashboard/_layout/quote-results'
    | '/dashboard/_layout/services'
    | '/driver/_layout/available'
    | '/driver/_layout/dashboard'
    | '/driver/_layout/history'
    | '/driver/_layout/onboarding'
    | '/driver/_layout/profile'
    | '/driver/_layout/settings'
    | '/driver/_layout/trips'
    | '/my-bookings/_layout/dashboard'
    | '/my-bookings/_layout/history'
    | '/my-bookings/_layout/trips'
    | '/driver/_layout/'
    | '/my-bookings/_layout/'
    | '/admin/dashboard/_layout/settings'
    | '/dashboard/_layout/book-appointment/$carId'
    | '/dashboard/_layout/book-service/$serviceId'
    | '/dashboard/_layout/car-details/$carId'
    | '/admin/dashboard/_layout/'
    | '/admin/dashboard/_layout/cars/add-car'
    | '/admin/dashboard/_layout/drivers/onboarding'
    | '/admin/dashboard/_layout/settings/account'
    | '/admin/dashboard/_layout/settings/security'
    | '/admin/dashboard/_layout/admin-testing/'
    | '/admin/dashboard/_layout/analytics/'
    | '/admin/dashboard/_layout/board/'
    | '/admin/dashboard/_layout/bookings/'
    | '/admin/dashboard/_layout/bookmarks/'
    | '/admin/dashboard/_layout/cars/'
    | '/admin/dashboard/_layout/drivers/'
    | '/admin/dashboard/_layout/inbox/'
    | '/admin/dashboard/_layout/invoices/'
    | '/admin/dashboard/_layout/packages/'
    | '/admin/dashboard/_layout/pricing-config/'
    | '/admin/dashboard/_layout/publications/'
    | '/admin/dashboard/_layout/published/'
    | '/admin/dashboard/_layout/report/'
    | '/admin/dashboard/_layout/settings/'
    | '/admin/dashboard/_layout/todays-scheduled/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/my-bookings/_layout': {
      id: '/my-bookings/_layout'
      path: ''
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsLayoutRouteImport
      parentRoute: typeof MyBookingsRoute
    }
    '/driver/_layout': {
      id: '/driver/_layout'
      path: ''
      fullPath: '/driver'
      preLoaderRoute: typeof DriverLayoutRouteImport
      parentRoute: typeof DriverRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/terms-and-conditions': {
      id: '/_marketing/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof MarketingTermsAndConditionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/services': {
      id: '/_marketing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MarketingServicesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/select-vehicle': {
      id: '/_marketing/select-vehicle'
      path: '/select-vehicle'
      fullPath: '/select-vehicle'
      preLoaderRoute: typeof MarketingSelectVehicleRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/quote-results': {
      id: '/_marketing/quote-results'
      path: '/quote-results'
      fullPath: '/quote-results'
      preLoaderRoute: typeof MarketingQuoteResultsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/profile': {
      id: '/_marketing/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MarketingProfileRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/fleet': {
      id: '/_marketing/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof MarketingFleetRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faqs': {
      id: '/_marketing/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof MarketingFaqsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/dashboard': {
      id: '/_marketing/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MarketingDashboardRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact-us': {
      id: '/_marketing/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof MarketingContactUsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/calculate-quote': {
      id: '/_marketing/calculate-quote'
      path: '/calculate-quote'
      fullPath: '/calculate-quote'
      preLoaderRoute: typeof MarketingCalculateQuoteRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about-us': {
      id: '/_marketing/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof MarketingAboutUsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/my-bookings/_layout/': {
      id: '/my-bookings/_layout/'
      path: '/'
      fullPath: '/my-bookings/'
      preLoaderRoute: typeof MyBookingsLayoutIndexRouteImport
      parentRoute: typeof MyBookingsLayoutRoute
    }
    '/driver/_layout/': {
      id: '/driver/_layout/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverLayoutIndexRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/my-bookings/_layout/trips': {
      id: '/my-bookings/_layout/trips'
      path: '/trips'
      fullPath: '/my-bookings/trips'
      preLoaderRoute: typeof MyBookingsLayoutTripsRouteImport
      parentRoute: typeof MyBookingsLayoutRoute
    }
    '/my-bookings/_layout/history': {
      id: '/my-bookings/_layout/history'
      path: '/history'
      fullPath: '/my-bookings/history'
      preLoaderRoute: typeof MyBookingsLayoutHistoryRouteImport
      parentRoute: typeof MyBookingsLayoutRoute
    }
    '/my-bookings/_layout/dashboard': {
      id: '/my-bookings/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/my-bookings/dashboard'
      preLoaderRoute: typeof MyBookingsLayoutDashboardRouteImport
      parentRoute: typeof MyBookingsLayoutRoute
    }
    '/driver/_layout/trips': {
      id: '/driver/_layout/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverLayoutTripsRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/settings': {
      id: '/driver/_layout/settings'
      path: '/settings'
      fullPath: '/driver/settings'
      preLoaderRoute: typeof DriverLayoutSettingsRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/profile': {
      id: '/driver/_layout/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverLayoutProfileRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/onboarding': {
      id: '/driver/_layout/onboarding'
      path: '/onboarding'
      fullPath: '/driver/onboarding'
      preLoaderRoute: typeof DriverLayoutOnboardingRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/history': {
      id: '/driver/_layout/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverLayoutHistoryRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/dashboard': {
      id: '/driver/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverLayoutDashboardRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/available': {
      id: '/driver/_layout/available'
      path: '/available'
      fullPath: '/driver/available'
      preLoaderRoute: typeof DriverLayoutAvailableRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/dashboard/_layout/services': {
      id: '/dashboard/_layout/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardLayoutServicesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/quote-results': {
      id: '/dashboard/_layout/quote-results'
      path: '/quote-results'
      fullPath: '/dashboard/quote-results'
      preLoaderRoute: typeof DashboardLayoutQuoteResultsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/instant-quote': {
      id: '/dashboard/_layout/instant-quote'
      path: '/instant-quote'
      fullPath: '/dashboard/instant-quote'
      preLoaderRoute: typeof DashboardLayoutInstantQuoteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/cars': {
      id: '/dashboard/_layout/cars'
      path: '/cars'
      fullPath: '/dashboard/cars'
      preLoaderRoute: typeof DashboardLayoutCarsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/calculate-quote': {
      id: '/dashboard/_layout/calculate-quote'
      path: '/calculate-quote'
      fullPath: '/dashboard/calculate-quote'
      preLoaderRoute: typeof DashboardLayoutCalculateQuoteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/book-appointment': {
      id: '/dashboard/_layout/book-appointment'
      path: '/book-appointment'
      fullPath: '/dashboard/book-appointment'
      preLoaderRoute: typeof DashboardLayoutBookAppointmentRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/admin/dashboard/_layout': {
      id: '/admin/dashboard/_layout'
      path: ''
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLayoutRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_marketing/book-service/$serviceId': {
      id: '/_marketing/book-service/$serviceId'
      path: '/book-service/$serviceId'
      fullPath: '/book-service/$serviceId'
      preLoaderRoute: typeof MarketingBookServiceServiceIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/book-quote/$quoteId': {
      id: '/_marketing/book-quote/$quoteId'
      path: '/book-quote/$quoteId'
      fullPath: '/book-quote/$quoteId'
      preLoaderRoute: typeof MarketingBookQuoteQuoteIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/book-car/$carId': {
      id: '/_marketing/book-car/$carId'
      path: '/book-car/$carId'
      fullPath: '/book-car/$carId'
      preLoaderRoute: typeof MarketingBookCarCarIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/account/settings': {
      id: '/_marketing/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof MarketingAccountSettingsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/admin/dashboard/_layout/': {
      id: '/admin/dashboard/_layout/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardLayoutIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/dashboard/_layout/car-details/$carId': {
      id: '/dashboard/_layout/car-details/$carId'
      path: '/car-details/$carId'
      fullPath: '/dashboard/car-details/$carId'
      preLoaderRoute: typeof DashboardLayoutCarDetailsCarIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/book-service/$serviceId': {
      id: '/dashboard/_layout/book-service/$serviceId'
      path: '/book-service/$serviceId'
      fullPath: '/dashboard/book-service/$serviceId'
      preLoaderRoute: typeof DashboardLayoutBookServiceServiceIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/book-appointment/$carId': {
      id: '/dashboard/_layout/book-appointment/$carId'
      path: '/$carId'
      fullPath: '/dashboard/book-appointment/$carId'
      preLoaderRoute: typeof DashboardLayoutBookAppointmentCarIdRouteImport
      parentRoute: typeof DashboardLayoutBookAppointmentRoute
    }
    '/admin/dashboard/_layout/settings': {
      id: '/admin/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardLayoutSettingsRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/todays-scheduled/': {
      id: '/admin/dashboard/_layout/todays-scheduled/'
      path: '/todays-scheduled'
      fullPath: '/admin/dashboard/todays-scheduled'
      preLoaderRoute: typeof AdminDashboardLayoutTodaysScheduledIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/settings/': {
      id: '/admin/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/admin/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutSettingsRoute
    }
    '/admin/dashboard/_layout/report/': {
      id: '/admin/dashboard/_layout/report/'
      path: '/report'
      fullPath: '/admin/dashboard/report'
      preLoaderRoute: typeof AdminDashboardLayoutReportIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/published/': {
      id: '/admin/dashboard/_layout/published/'
      path: '/published'
      fullPath: '/admin/dashboard/published'
      preLoaderRoute: typeof AdminDashboardLayoutPublishedIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/publications/': {
      id: '/admin/dashboard/_layout/publications/'
      path: '/publications'
      fullPath: '/admin/dashboard/publications'
      preLoaderRoute: typeof AdminDashboardLayoutPublicationsIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/pricing-config/': {
      id: '/admin/dashboard/_layout/pricing-config/'
      path: '/pricing-config'
      fullPath: '/admin/dashboard/pricing-config'
      preLoaderRoute: typeof AdminDashboardLayoutPricingConfigIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/packages/': {
      id: '/admin/dashboard/_layout/packages/'
      path: '/packages'
      fullPath: '/admin/dashboard/packages'
      preLoaderRoute: typeof AdminDashboardLayoutPackagesIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/invoices/': {
      id: '/admin/dashboard/_layout/invoices/'
      path: '/invoices'
      fullPath: '/admin/dashboard/invoices'
      preLoaderRoute: typeof AdminDashboardLayoutInvoicesIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/inbox/': {
      id: '/admin/dashboard/_layout/inbox/'
      path: '/inbox'
      fullPath: '/admin/dashboard/inbox'
      preLoaderRoute: typeof AdminDashboardLayoutInboxIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/drivers/': {
      id: '/admin/dashboard/_layout/drivers/'
      path: '/drivers'
      fullPath: '/admin/dashboard/drivers'
      preLoaderRoute: typeof AdminDashboardLayoutDriversIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/cars/': {
      id: '/admin/dashboard/_layout/cars/'
      path: '/cars'
      fullPath: '/admin/dashboard/cars'
      preLoaderRoute: typeof AdminDashboardLayoutCarsIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/bookmarks/': {
      id: '/admin/dashboard/_layout/bookmarks/'
      path: '/bookmarks'
      fullPath: '/admin/dashboard/bookmarks'
      preLoaderRoute: typeof AdminDashboardLayoutBookmarksIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/bookings/': {
      id: '/admin/dashboard/_layout/bookings/'
      path: '/bookings'
      fullPath: '/admin/dashboard/bookings'
      preLoaderRoute: typeof AdminDashboardLayoutBookingsIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/board/': {
      id: '/admin/dashboard/_layout/board/'
      path: '/board'
      fullPath: '/admin/dashboard/board'
      preLoaderRoute: typeof AdminDashboardLayoutBoardIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/analytics/': {
      id: '/admin/dashboard/_layout/analytics/'
      path: '/analytics'
      fullPath: '/admin/dashboard/analytics'
      preLoaderRoute: typeof AdminDashboardLayoutAnalyticsIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/admin-testing/': {
      id: '/admin/dashboard/_layout/admin-testing/'
      path: '/admin-testing'
      fullPath: '/admin/dashboard/admin-testing'
      preLoaderRoute: typeof AdminDashboardLayoutAdminTestingIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/settings/security': {
      id: '/admin/dashboard/_layout/settings/security'
      path: '/security'
      fullPath: '/admin/dashboard/settings/security'
      preLoaderRoute: typeof AdminDashboardLayoutSettingsSecurityRouteImport
      parentRoute: typeof AdminDashboardLayoutSettingsRoute
    }
    '/admin/dashboard/_layout/settings/account': {
      id: '/admin/dashboard/_layout/settings/account'
      path: '/account'
      fullPath: '/admin/dashboard/settings/account'
      preLoaderRoute: typeof AdminDashboardLayoutSettingsAccountRouteImport
      parentRoute: typeof AdminDashboardLayoutSettingsRoute
    }
    '/admin/dashboard/_layout/drivers/onboarding': {
      id: '/admin/dashboard/_layout/drivers/onboarding'
      path: '/drivers/onboarding'
      fullPath: '/admin/dashboard/drivers/onboarding'
      preLoaderRoute: typeof AdminDashboardLayoutDriversOnboardingRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/dashboard/_layout/cars/add-car': {
      id: '/admin/dashboard/_layout/cars/add-car'
      path: '/cars/add-car'
      fullPath: '/admin/dashboard/cars/add-car'
      preLoaderRoute: typeof AdminDashboardLayoutCarsAddCarRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutUsRoute: typeof MarketingAboutUsRoute
  MarketingCalculateQuoteRoute: typeof MarketingCalculateQuoteRoute
  MarketingContactUsRoute: typeof MarketingContactUsRoute
  MarketingDashboardRoute: typeof MarketingDashboardRoute
  MarketingFaqsRoute: typeof MarketingFaqsRoute
  MarketingFleetRoute: typeof MarketingFleetRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingProfileRoute: typeof MarketingProfileRoute
  MarketingQuoteResultsRoute: typeof MarketingQuoteResultsRoute
  MarketingSelectVehicleRoute: typeof MarketingSelectVehicleRoute
  MarketingServicesRoute: typeof MarketingServicesRoute
  MarketingTermsAndConditionsRoute: typeof MarketingTermsAndConditionsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingAccountSettingsRoute: typeof MarketingAccountSettingsRoute
  MarketingBookCarCarIdRoute: typeof MarketingBookCarCarIdRoute
  MarketingBookQuoteQuoteIdRoute: typeof MarketingBookQuoteQuoteIdRoute
  MarketingBookServiceServiceIdRoute: typeof MarketingBookServiceServiceIdRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutUsRoute: MarketingAboutUsRoute,
  MarketingCalculateQuoteRoute: MarketingCalculateQuoteRoute,
  MarketingContactUsRoute: MarketingContactUsRoute,
  MarketingDashboardRoute: MarketingDashboardRoute,
  MarketingFaqsRoute: MarketingFaqsRoute,
  MarketingFleetRoute: MarketingFleetRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingProfileRoute: MarketingProfileRoute,
  MarketingQuoteResultsRoute: MarketingQuoteResultsRoute,
  MarketingSelectVehicleRoute: MarketingSelectVehicleRoute,
  MarketingServicesRoute: MarketingServicesRoute,
  MarketingTermsAndConditionsRoute: MarketingTermsAndConditionsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingAccountSettingsRoute: MarketingAccountSettingsRoute,
  MarketingBookCarCarIdRoute: MarketingBookCarCarIdRoute,
  MarketingBookQuoteQuoteIdRoute: MarketingBookQuoteQuoteIdRoute,
  MarketingBookServiceServiceIdRoute: MarketingBookServiceServiceIdRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
