/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as MarketingServicesRouteImport } from './routes/_marketing/services'
import { Route as MarketingFaqsRouteImport } from './routes/_marketing/faqs'
import { Route as MarketingContactUsRouteImport } from './routes/_marketing/contact-us'
import { Route as MarketingBookingRouteImport } from './routes/_marketing/booking'
import { Route as MarketingAboutUsRouteImport } from './routes/_marketing/about-us'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutTodaysScheduledIndexRouteImport } from './routes/dashboard/_layout/todays-scheduled/index'
import { Route as DashboardLayoutSettingsIndexRouteImport } from './routes/dashboard/_layout/settings/index'
import { Route as DashboardLayoutReportIndexRouteImport } from './routes/dashboard/_layout/report/index'
import { Route as DashboardLayoutPublishedIndexRouteImport } from './routes/dashboard/_layout/published/index'
import { Route as DashboardLayoutPackagesIndexRouteImport } from './routes/dashboard/_layout/packages/index'
import { Route as DashboardLayoutInboxIndexRouteImport } from './routes/dashboard/_layout/inbox/index'
import { Route as DashboardLayoutCarManagementIndexRouteImport } from './routes/dashboard/_layout/car-management/index'
import { Route as DashboardLayoutBookmarksIndexRouteImport } from './routes/dashboard/_layout/bookmarks/index'
import { Route as DashboardLayoutBoardIndexRouteImport } from './routes/dashboard/_layout/board/index'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingServicesRoute = MarketingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqsRoute = MarketingFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactUsRoute = MarketingContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBookingRoute = MarketingBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutUsRoute = MarketingAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutTodaysScheduledIndexRoute =
  DashboardLayoutTodaysScheduledIndexRouteImport.update({
    id: '/todays-scheduled/',
    path: '/todays-scheduled/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsIndexRoute =
  DashboardLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutReportIndexRoute =
  DashboardLayoutReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPublishedIndexRoute =
  DashboardLayoutPublishedIndexRouteImport.update({
    id: '/published/',
    path: '/published/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPackagesIndexRoute =
  DashboardLayoutPackagesIndexRouteImport.update({
    id: '/packages/',
    path: '/packages/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInboxIndexRoute =
  DashboardLayoutInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCarManagementIndexRoute =
  DashboardLayoutCarManagementIndexRouteImport.update({
    id: '/car-management/',
    path: '/car-management/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBookmarksIndexRoute =
  DashboardLayoutBookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBoardIndexRoute =
  DashboardLayoutBoardIndexRouteImport.update({
    id: '/board/',
    path: '/board/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about-us': typeof MarketingAboutUsRoute
  '/booking': typeof MarketingBookingRoute
  '/contact-us': typeof MarketingContactUsRoute
  '/faqs': typeof MarketingFaqsRoute
  '/services': typeof MarketingServicesRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/board': typeof DashboardLayoutBoardIndexRoute
  '/dashboard/bookmarks': typeof DashboardLayoutBookmarksIndexRoute
  '/dashboard/car-management': typeof DashboardLayoutCarManagementIndexRoute
  '/dashboard/inbox': typeof DashboardLayoutInboxIndexRoute
  '/dashboard/packages': typeof DashboardLayoutPackagesIndexRoute
  '/dashboard/published': typeof DashboardLayoutPublishedIndexRoute
  '/dashboard/report': typeof DashboardLayoutReportIndexRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/todays-scheduled': typeof DashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about-us': typeof MarketingAboutUsRoute
  '/booking': typeof MarketingBookingRoute
  '/contact-us': typeof MarketingContactUsRoute
  '/faqs': typeof MarketingFaqsRoute
  '/services': typeof MarketingServicesRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/': typeof MarketingIndexRoute
  '/dashboard/board': typeof DashboardLayoutBoardIndexRoute
  '/dashboard/bookmarks': typeof DashboardLayoutBookmarksIndexRoute
  '/dashboard/car-management': typeof DashboardLayoutCarManagementIndexRoute
  '/dashboard/inbox': typeof DashboardLayoutInboxIndexRoute
  '/dashboard/packages': typeof DashboardLayoutPackagesIndexRoute
  '/dashboard/published': typeof DashboardLayoutPublishedIndexRoute
  '/dashboard/report': typeof DashboardLayoutReportIndexRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/todays-scheduled': typeof DashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_marketing/about-us': typeof MarketingAboutUsRoute
  '/_marketing/booking': typeof MarketingBookingRoute
  '/_marketing/contact-us': typeof MarketingContactUsRoute
  '/_marketing/faqs': typeof MarketingFaqsRoute
  '/_marketing/services': typeof MarketingServicesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/board/': typeof DashboardLayoutBoardIndexRoute
  '/dashboard/_layout/bookmarks/': typeof DashboardLayoutBookmarksIndexRoute
  '/dashboard/_layout/car-management/': typeof DashboardLayoutCarManagementIndexRoute
  '/dashboard/_layout/inbox/': typeof DashboardLayoutInboxIndexRoute
  '/dashboard/_layout/packages/': typeof DashboardLayoutPackagesIndexRoute
  '/dashboard/_layout/published/': typeof DashboardLayoutPublishedIndexRoute
  '/dashboard/_layout/report/': typeof DashboardLayoutReportIndexRoute
  '/dashboard/_layout/settings/': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/_layout/todays-scheduled/': typeof DashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/about-us'
    | '/booking'
    | '/contact-us'
    | '/faqs'
    | '/services'
    | '/dashboard'
    | '/'
    | '/dashboard/'
    | '/dashboard/board'
    | '/dashboard/bookmarks'
    | '/dashboard/car-management'
    | '/dashboard/inbox'
    | '/dashboard/packages'
    | '/dashboard/published'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/todays-scheduled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/about-us'
    | '/booking'
    | '/contact-us'
    | '/faqs'
    | '/services'
    | '/dashboard'
    | '/'
    | '/dashboard/board'
    | '/dashboard/bookmarks'
    | '/dashboard/car-management'
    | '/dashboard/inbox'
    | '/dashboard/packages'
    | '/dashboard/published'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/todays-scheduled'
  id:
    | '__root__'
    | '/_marketing'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_marketing/about-us'
    | '/_marketing/booking'
    | '/_marketing/contact-us'
    | '/_marketing/faqs'
    | '/_marketing/services'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/_marketing/'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/board/'
    | '/dashboard/_layout/bookmarks/'
    | '/dashboard/_layout/car-management/'
    | '/dashboard/_layout/inbox/'
    | '/dashboard/_layout/packages/'
    | '/dashboard/_layout/published/'
    | '/dashboard/_layout/report/'
    | '/dashboard/_layout/settings/'
    | '/dashboard/_layout/todays-scheduled/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/services': {
      id: '/_marketing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MarketingServicesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faqs': {
      id: '/_marketing/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof MarketingFaqsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact-us': {
      id: '/_marketing/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof MarketingContactUsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/booking': {
      id: '/_marketing/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof MarketingBookingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about-us': {
      id: '/_marketing/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof MarketingAboutUsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/todays-scheduled/': {
      id: '/dashboard/_layout/todays-scheduled/'
      path: '/todays-scheduled'
      fullPath: '/dashboard/todays-scheduled'
      preLoaderRoute: typeof DashboardLayoutTodaysScheduledIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/': {
      id: '/dashboard/_layout/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/report/': {
      id: '/dashboard/_layout/report/'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardLayoutReportIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/published/': {
      id: '/dashboard/_layout/published/'
      path: '/published'
      fullPath: '/dashboard/published'
      preLoaderRoute: typeof DashboardLayoutPublishedIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/packages/': {
      id: '/dashboard/_layout/packages/'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardLayoutPackagesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/inbox/': {
      id: '/dashboard/_layout/inbox/'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardLayoutInboxIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/car-management/': {
      id: '/dashboard/_layout/car-management/'
      path: '/car-management'
      fullPath: '/dashboard/car-management'
      preLoaderRoute: typeof DashboardLayoutCarManagementIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/bookmarks/': {
      id: '/dashboard/_layout/bookmarks/'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardLayoutBookmarksIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/board/': {
      id: '/dashboard/_layout/board/'
      path: '/board'
      fullPath: '/dashboard/board'
      preLoaderRoute: typeof DashboardLayoutBoardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutUsRoute: typeof MarketingAboutUsRoute
  MarketingBookingRoute: typeof MarketingBookingRoute
  MarketingContactUsRoute: typeof MarketingContactUsRoute
  MarketingFaqsRoute: typeof MarketingFaqsRoute
  MarketingServicesRoute: typeof MarketingServicesRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutUsRoute: MarketingAboutUsRoute,
  MarketingBookingRoute: MarketingBookingRoute,
  MarketingContactUsRoute: MarketingContactUsRoute,
  MarketingFaqsRoute: MarketingFaqsRoute,
  MarketingServicesRoute: MarketingServicesRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutBoardIndexRoute: typeof DashboardLayoutBoardIndexRoute
  DashboardLayoutBookmarksIndexRoute: typeof DashboardLayoutBookmarksIndexRoute
  DashboardLayoutCarManagementIndexRoute: typeof DashboardLayoutCarManagementIndexRoute
  DashboardLayoutInboxIndexRoute: typeof DashboardLayoutInboxIndexRoute
  DashboardLayoutPackagesIndexRoute: typeof DashboardLayoutPackagesIndexRoute
  DashboardLayoutPublishedIndexRoute: typeof DashboardLayoutPublishedIndexRoute
  DashboardLayoutReportIndexRoute: typeof DashboardLayoutReportIndexRoute
  DashboardLayoutSettingsIndexRoute: typeof DashboardLayoutSettingsIndexRoute
  DashboardLayoutTodaysScheduledIndexRoute: typeof DashboardLayoutTodaysScheduledIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutBoardIndexRoute: DashboardLayoutBoardIndexRoute,
  DashboardLayoutBookmarksIndexRoute: DashboardLayoutBookmarksIndexRoute,
  DashboardLayoutCarManagementIndexRoute:
    DashboardLayoutCarManagementIndexRoute,
  DashboardLayoutInboxIndexRoute: DashboardLayoutInboxIndexRoute,
  DashboardLayoutPackagesIndexRoute: DashboardLayoutPackagesIndexRoute,
  DashboardLayoutPublishedIndexRoute: DashboardLayoutPublishedIndexRoute,
  DashboardLayoutReportIndexRoute: DashboardLayoutReportIndexRoute,
  DashboardLayoutSettingsIndexRoute: DashboardLayoutSettingsIndexRoute,
  DashboardLayoutTodaysScheduledIndexRoute:
    DashboardLayoutTodaysScheduledIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
