/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DriverLayoutRouteImport } from './routes/driver/_layout'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as CustomerLayoutRouteImport } from './routes/customer/_layout'
import { Route as MarketingTermsAndConditionsRouteImport } from './routes/_marketing/terms-and-conditions'
import { Route as MarketingServicesRouteImport } from './routes/_marketing/services'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingFaqsRouteImport } from './routes/_marketing/faqs'
import { Route as MarketingContactUsRouteImport } from './routes/_marketing/contact-us'
import { Route as MarketingBookingRouteImport } from './routes/_marketing/booking'
import { Route as MarketingAboutUsRouteImport } from './routes/_marketing/about-us'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as DriverLayoutIndexRouteImport } from './routes/driver/_layout/index'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as CustomerLayoutIndexRouteImport } from './routes/customer/_layout/index'
import { Route as DriverLayoutTripsRouteImport } from './routes/driver/_layout/trips'
import { Route as DriverLayoutSettingsRouteImport } from './routes/driver/_layout/settings'
import { Route as DriverLayoutProfileRouteImport } from './routes/driver/_layout/profile'
import { Route as DriverLayoutOnboardingRouteImport } from './routes/driver/_layout/onboarding'
import { Route as CustomerLayoutServicesRouteImport } from './routes/customer/_layout/services'
import { Route as CustomerLayoutProfileRouteImport } from './routes/customer/_layout/profile'
import { Route as CustomerLayoutInstantQuoteRouteImport } from './routes/customer/_layout/instant-quote'
import { Route as CustomerLayoutBookingsRouteImport } from './routes/customer/_layout/bookings'
import { Route as DashboardLayoutTodaysScheduledIndexRouteImport } from './routes/dashboard/_layout/todays-scheduled/index'
import { Route as DashboardLayoutSettingsIndexRouteImport } from './routes/dashboard/_layout/settings/index'
import { Route as DashboardLayoutReportIndexRouteImport } from './routes/dashboard/_layout/report/index'
import { Route as DashboardLayoutPublishedIndexRouteImport } from './routes/dashboard/_layout/published/index'
import { Route as DashboardLayoutPublicationsIndexRouteImport } from './routes/dashboard/_layout/publications/index'
import { Route as DashboardLayoutPricingConfigIndexRouteImport } from './routes/dashboard/_layout/pricing-config/index'
import { Route as DashboardLayoutPackagesIndexRouteImport } from './routes/dashboard/_layout/packages/index'
import { Route as DashboardLayoutInboxIndexRouteImport } from './routes/dashboard/_layout/inbox/index'
import { Route as DashboardLayoutDriversIndexRouteImport } from './routes/dashboard/_layout/drivers/index'
import { Route as DashboardLayoutCarsIndexRouteImport } from './routes/dashboard/_layout/cars/index'
import { Route as DashboardLayoutBookmarksIndexRouteImport } from './routes/dashboard/_layout/bookmarks/index'
import { Route as DashboardLayoutBookingsIndexRouteImport } from './routes/dashboard/_layout/bookings/index'
import { Route as DashboardLayoutBoardIndexRouteImport } from './routes/dashboard/_layout/board/index'
import { Route as DashboardLayoutAnalyticsIndexRouteImport } from './routes/dashboard/_layout/analytics/index'
import { Route as DashboardLayoutAdminTestingIndexRouteImport } from './routes/dashboard/_layout/admin-testing/index'
import { Route as DashboardLayoutDriversOnboardingRouteImport } from './routes/dashboard/_layout/drivers/onboarding'
import { Route as DashboardLayoutCarsAddCarRouteImport } from './routes/dashboard/_layout/cars/add-car'
import { Route as CustomerLayoutBookServiceServiceIdRouteImport } from './routes/customer/_layout/book-service/$serviceId'
import { Route as CustomerLayoutAccountSettingsRouteImport } from './routes/customer/_layout/account/settings'

const DriverRouteImport = createFileRoute('/driver')()
const DashboardRouteImport = createFileRoute('/dashboard')()
const CustomerRouteImport = createFileRoute('/customer')()

const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DriverLayoutRoute = DriverLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DriverRoute,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const CustomerLayoutRoute = CustomerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CustomerRoute,
} as any)
const MarketingTermsAndConditionsRoute =
  MarketingTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingServicesRoute = MarketingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqsRoute = MarketingFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactUsRoute = MarketingContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBookingRoute = MarketingBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutUsRoute = MarketingAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLayoutIndexRoute = DriverLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const CustomerLayoutIndexRoute = CustomerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const DriverLayoutTripsRoute = DriverLayoutTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutSettingsRoute = DriverLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutProfileRoute = DriverLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const DriverLayoutOnboardingRoute = DriverLayoutOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DriverLayoutRoute,
} as any)
const CustomerLayoutServicesRoute = CustomerLayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const CustomerLayoutProfileRoute = CustomerLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const CustomerLayoutInstantQuoteRoute =
  CustomerLayoutInstantQuoteRouteImport.update({
    id: '/instant-quote',
    path: '/instant-quote',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)
const CustomerLayoutBookingsRoute = CustomerLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const DashboardLayoutTodaysScheduledIndexRoute =
  DashboardLayoutTodaysScheduledIndexRouteImport.update({
    id: '/todays-scheduled/',
    path: '/todays-scheduled/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsIndexRoute =
  DashboardLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutReportIndexRoute =
  DashboardLayoutReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPublishedIndexRoute =
  DashboardLayoutPublishedIndexRouteImport.update({
    id: '/published/',
    path: '/published/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPublicationsIndexRoute =
  DashboardLayoutPublicationsIndexRouteImport.update({
    id: '/publications/',
    path: '/publications/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPricingConfigIndexRoute =
  DashboardLayoutPricingConfigIndexRouteImport.update({
    id: '/pricing-config/',
    path: '/pricing-config/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPackagesIndexRoute =
  DashboardLayoutPackagesIndexRouteImport.update({
    id: '/packages/',
    path: '/packages/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInboxIndexRoute =
  DashboardLayoutInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDriversIndexRoute =
  DashboardLayoutDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCarsIndexRoute =
  DashboardLayoutCarsIndexRouteImport.update({
    id: '/cars/',
    path: '/cars/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBookmarksIndexRoute =
  DashboardLayoutBookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBookingsIndexRoute =
  DashboardLayoutBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBoardIndexRoute =
  DashboardLayoutBoardIndexRouteImport.update({
    id: '/board/',
    path: '/board/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutAnalyticsIndexRoute =
  DashboardLayoutAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutAdminTestingIndexRoute =
  DashboardLayoutAdminTestingIndexRouteImport.update({
    id: '/admin-testing/',
    path: '/admin-testing/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDriversOnboardingRoute =
  DashboardLayoutDriversOnboardingRouteImport.update({
    id: '/drivers/onboarding',
    path: '/drivers/onboarding',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCarsAddCarRoute =
  DashboardLayoutCarsAddCarRouteImport.update({
    id: '/cars/add-car',
    path: '/cars/add-car',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const CustomerLayoutBookServiceServiceIdRoute =
  CustomerLayoutBookServiceServiceIdRouteImport.update({
    id: '/book-service/$serviceId',
    path: '/book-service/$serviceId',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)
const CustomerLayoutAccountSettingsRoute =
  CustomerLayoutAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about-us': typeof MarketingAboutUsRoute
  '/booking': typeof MarketingBookingRoute
  '/contact-us': typeof MarketingContactUsRoute
  '/faqs': typeof MarketingFaqsRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/services': typeof MarketingServicesRoute
  '/terms-and-conditions': typeof MarketingTermsAndConditionsRoute
  '/customer': typeof CustomerLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/driver': typeof DriverLayoutRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/customer/bookings': typeof CustomerLayoutBookingsRoute
  '/customer/instant-quote': typeof CustomerLayoutInstantQuoteRoute
  '/customer/profile': typeof CustomerLayoutProfileRoute
  '/customer/services': typeof CustomerLayoutServicesRoute
  '/driver/onboarding': typeof DriverLayoutOnboardingRoute
  '/driver/profile': typeof DriverLayoutProfileRoute
  '/driver/settings': typeof DriverLayoutSettingsRoute
  '/driver/trips': typeof DriverLayoutTripsRoute
  '/customer/': typeof CustomerLayoutIndexRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/driver/': typeof DriverLayoutIndexRoute
  '/customer/account/settings': typeof CustomerLayoutAccountSettingsRoute
  '/customer/book-service/$serviceId': typeof CustomerLayoutBookServiceServiceIdRoute
  '/dashboard/cars/add-car': typeof DashboardLayoutCarsAddCarRoute
  '/dashboard/drivers/onboarding': typeof DashboardLayoutDriversOnboardingRoute
  '/dashboard/admin-testing': typeof DashboardLayoutAdminTestingIndexRoute
  '/dashboard/analytics': typeof DashboardLayoutAnalyticsIndexRoute
  '/dashboard/board': typeof DashboardLayoutBoardIndexRoute
  '/dashboard/bookings': typeof DashboardLayoutBookingsIndexRoute
  '/dashboard/bookmarks': typeof DashboardLayoutBookmarksIndexRoute
  '/dashboard/cars': typeof DashboardLayoutCarsIndexRoute
  '/dashboard/drivers': typeof DashboardLayoutDriversIndexRoute
  '/dashboard/inbox': typeof DashboardLayoutInboxIndexRoute
  '/dashboard/packages': typeof DashboardLayoutPackagesIndexRoute
  '/dashboard/pricing-config': typeof DashboardLayoutPricingConfigIndexRoute
  '/dashboard/publications': typeof DashboardLayoutPublicationsIndexRoute
  '/dashboard/published': typeof DashboardLayoutPublishedIndexRoute
  '/dashboard/report': typeof DashboardLayoutReportIndexRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/todays-scheduled': typeof DashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about-us': typeof MarketingAboutUsRoute
  '/booking': typeof MarketingBookingRoute
  '/contact-us': typeof MarketingContactUsRoute
  '/faqs': typeof MarketingFaqsRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/services': typeof MarketingServicesRoute
  '/terms-and-conditions': typeof MarketingTermsAndConditionsRoute
  '/customer': typeof CustomerLayoutIndexRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/driver': typeof DriverLayoutIndexRoute
  '/': typeof MarketingIndexRoute
  '/customer/bookings': typeof CustomerLayoutBookingsRoute
  '/customer/instant-quote': typeof CustomerLayoutInstantQuoteRoute
  '/customer/profile': typeof CustomerLayoutProfileRoute
  '/customer/services': typeof CustomerLayoutServicesRoute
  '/driver/onboarding': typeof DriverLayoutOnboardingRoute
  '/driver/profile': typeof DriverLayoutProfileRoute
  '/driver/settings': typeof DriverLayoutSettingsRoute
  '/driver/trips': typeof DriverLayoutTripsRoute
  '/customer/account/settings': typeof CustomerLayoutAccountSettingsRoute
  '/customer/book-service/$serviceId': typeof CustomerLayoutBookServiceServiceIdRoute
  '/dashboard/cars/add-car': typeof DashboardLayoutCarsAddCarRoute
  '/dashboard/drivers/onboarding': typeof DashboardLayoutDriversOnboardingRoute
  '/dashboard/admin-testing': typeof DashboardLayoutAdminTestingIndexRoute
  '/dashboard/analytics': typeof DashboardLayoutAnalyticsIndexRoute
  '/dashboard/board': typeof DashboardLayoutBoardIndexRoute
  '/dashboard/bookings': typeof DashboardLayoutBookingsIndexRoute
  '/dashboard/bookmarks': typeof DashboardLayoutBookmarksIndexRoute
  '/dashboard/cars': typeof DashboardLayoutCarsIndexRoute
  '/dashboard/drivers': typeof DashboardLayoutDriversIndexRoute
  '/dashboard/inbox': typeof DashboardLayoutInboxIndexRoute
  '/dashboard/packages': typeof DashboardLayoutPackagesIndexRoute
  '/dashboard/pricing-config': typeof DashboardLayoutPricingConfigIndexRoute
  '/dashboard/publications': typeof DashboardLayoutPublicationsIndexRoute
  '/dashboard/published': typeof DashboardLayoutPublishedIndexRoute
  '/dashboard/report': typeof DashboardLayoutReportIndexRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/todays-scheduled': typeof DashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_marketing/about-us': typeof MarketingAboutUsRoute
  '/_marketing/booking': typeof MarketingBookingRoute
  '/_marketing/contact-us': typeof MarketingContactUsRoute
  '/_marketing/faqs': typeof MarketingFaqsRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/services': typeof MarketingServicesRoute
  '/_marketing/terms-and-conditions': typeof MarketingTermsAndConditionsRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/_layout': typeof CustomerLayoutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/driver/_layout': typeof DriverLayoutRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/customer/_layout/bookings': typeof CustomerLayoutBookingsRoute
  '/customer/_layout/instant-quote': typeof CustomerLayoutInstantQuoteRoute
  '/customer/_layout/profile': typeof CustomerLayoutProfileRoute
  '/customer/_layout/services': typeof CustomerLayoutServicesRoute
  '/driver/_layout/onboarding': typeof DriverLayoutOnboardingRoute
  '/driver/_layout/profile': typeof DriverLayoutProfileRoute
  '/driver/_layout/settings': typeof DriverLayoutSettingsRoute
  '/driver/_layout/trips': typeof DriverLayoutTripsRoute
  '/customer/_layout/': typeof CustomerLayoutIndexRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/driver/_layout/': typeof DriverLayoutIndexRoute
  '/customer/_layout/account/settings': typeof CustomerLayoutAccountSettingsRoute
  '/customer/_layout/book-service/$serviceId': typeof CustomerLayoutBookServiceServiceIdRoute
  '/dashboard/_layout/cars/add-car': typeof DashboardLayoutCarsAddCarRoute
  '/dashboard/_layout/drivers/onboarding': typeof DashboardLayoutDriversOnboardingRoute
  '/dashboard/_layout/admin-testing/': typeof DashboardLayoutAdminTestingIndexRoute
  '/dashboard/_layout/analytics/': typeof DashboardLayoutAnalyticsIndexRoute
  '/dashboard/_layout/board/': typeof DashboardLayoutBoardIndexRoute
  '/dashboard/_layout/bookings/': typeof DashboardLayoutBookingsIndexRoute
  '/dashboard/_layout/bookmarks/': typeof DashboardLayoutBookmarksIndexRoute
  '/dashboard/_layout/cars/': typeof DashboardLayoutCarsIndexRoute
  '/dashboard/_layout/drivers/': typeof DashboardLayoutDriversIndexRoute
  '/dashboard/_layout/inbox/': typeof DashboardLayoutInboxIndexRoute
  '/dashboard/_layout/packages/': typeof DashboardLayoutPackagesIndexRoute
  '/dashboard/_layout/pricing-config/': typeof DashboardLayoutPricingConfigIndexRoute
  '/dashboard/_layout/publications/': typeof DashboardLayoutPublicationsIndexRoute
  '/dashboard/_layout/published/': typeof DashboardLayoutPublishedIndexRoute
  '/dashboard/_layout/report/': typeof DashboardLayoutReportIndexRoute
  '/dashboard/_layout/settings/': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/_layout/todays-scheduled/': typeof DashboardLayoutTodaysScheduledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/about-us'
    | '/booking'
    | '/contact-us'
    | '/faqs'
    | '/privacy'
    | '/services'
    | '/terms-and-conditions'
    | '/customer'
    | '/dashboard'
    | '/driver'
    | '/'
    | '/customer/bookings'
    | '/customer/instant-quote'
    | '/customer/profile'
    | '/customer/services'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/settings'
    | '/driver/trips'
    | '/customer/'
    | '/dashboard/'
    | '/driver/'
    | '/customer/account/settings'
    | '/customer/book-service/$serviceId'
    | '/dashboard/cars/add-car'
    | '/dashboard/drivers/onboarding'
    | '/dashboard/admin-testing'
    | '/dashboard/analytics'
    | '/dashboard/board'
    | '/dashboard/bookings'
    | '/dashboard/bookmarks'
    | '/dashboard/cars'
    | '/dashboard/drivers'
    | '/dashboard/inbox'
    | '/dashboard/packages'
    | '/dashboard/pricing-config'
    | '/dashboard/publications'
    | '/dashboard/published'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/todays-scheduled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/about-us'
    | '/booking'
    | '/contact-us'
    | '/faqs'
    | '/privacy'
    | '/services'
    | '/terms-and-conditions'
    | '/customer'
    | '/dashboard'
    | '/driver'
    | '/'
    | '/customer/bookings'
    | '/customer/instant-quote'
    | '/customer/profile'
    | '/customer/services'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/settings'
    | '/driver/trips'
    | '/customer/account/settings'
    | '/customer/book-service/$serviceId'
    | '/dashboard/cars/add-car'
    | '/dashboard/drivers/onboarding'
    | '/dashboard/admin-testing'
    | '/dashboard/analytics'
    | '/dashboard/board'
    | '/dashboard/bookings'
    | '/dashboard/bookmarks'
    | '/dashboard/cars'
    | '/dashboard/drivers'
    | '/dashboard/inbox'
    | '/dashboard/packages'
    | '/dashboard/pricing-config'
    | '/dashboard/publications'
    | '/dashboard/published'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/todays-scheduled'
  id:
    | '__root__'
    | '/_marketing'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_marketing/about-us'
    | '/_marketing/booking'
    | '/_marketing/contact-us'
    | '/_marketing/faqs'
    | '/_marketing/privacy'
    | '/_marketing/services'
    | '/_marketing/terms-and-conditions'
    | '/customer'
    | '/customer/_layout'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/driver'
    | '/driver/_layout'
    | '/_marketing/'
    | '/customer/_layout/bookings'
    | '/customer/_layout/instant-quote'
    | '/customer/_layout/profile'
    | '/customer/_layout/services'
    | '/driver/_layout/onboarding'
    | '/driver/_layout/profile'
    | '/driver/_layout/settings'
    | '/driver/_layout/trips'
    | '/customer/_layout/'
    | '/dashboard/_layout/'
    | '/driver/_layout/'
    | '/customer/_layout/account/settings'
    | '/customer/_layout/book-service/$serviceId'
    | '/dashboard/_layout/cars/add-car'
    | '/dashboard/_layout/drivers/onboarding'
    | '/dashboard/_layout/admin-testing/'
    | '/dashboard/_layout/analytics/'
    | '/dashboard/_layout/board/'
    | '/dashboard/_layout/bookings/'
    | '/dashboard/_layout/bookmarks/'
    | '/dashboard/_layout/cars/'
    | '/dashboard/_layout/drivers/'
    | '/dashboard/_layout/inbox/'
    | '/dashboard/_layout/packages/'
    | '/dashboard/_layout/pricing-config/'
    | '/dashboard/_layout/publications/'
    | '/dashboard/_layout/published/'
    | '/dashboard/_layout/report/'
    | '/dashboard/_layout/settings/'
    | '/dashboard/_layout/todays-scheduled/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/driver/_layout': {
      id: '/driver/_layout'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverLayoutRouteImport
      parentRoute: typeof DriverRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/customer/_layout': {
      id: '/customer/_layout'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerLayoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_marketing/terms-and-conditions': {
      id: '/_marketing/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof MarketingTermsAndConditionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/services': {
      id: '/_marketing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MarketingServicesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faqs': {
      id: '/_marketing/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof MarketingFaqsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact-us': {
      id: '/_marketing/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof MarketingContactUsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/booking': {
      id: '/_marketing/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof MarketingBookingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about-us': {
      id: '/_marketing/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof MarketingAboutUsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/_layout/': {
      id: '/driver/_layout/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverLayoutIndexRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/customer/_layout/': {
      id: '/customer/_layout/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerLayoutIndexRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/driver/_layout/trips': {
      id: '/driver/_layout/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverLayoutTripsRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/settings': {
      id: '/driver/_layout/settings'
      path: '/settings'
      fullPath: '/driver/settings'
      preLoaderRoute: typeof DriverLayoutSettingsRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/profile': {
      id: '/driver/_layout/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverLayoutProfileRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/driver/_layout/onboarding': {
      id: '/driver/_layout/onboarding'
      path: '/onboarding'
      fullPath: '/driver/onboarding'
      preLoaderRoute: typeof DriverLayoutOnboardingRouteImport
      parentRoute: typeof DriverLayoutRoute
    }
    '/customer/_layout/services': {
      id: '/customer/_layout/services'
      path: '/services'
      fullPath: '/customer/services'
      preLoaderRoute: typeof CustomerLayoutServicesRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/profile': {
      id: '/customer/_layout/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerLayoutProfileRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/instant-quote': {
      id: '/customer/_layout/instant-quote'
      path: '/instant-quote'
      fullPath: '/customer/instant-quote'
      preLoaderRoute: typeof CustomerLayoutInstantQuoteRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/bookings': {
      id: '/customer/_layout/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerLayoutBookingsRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/dashboard/_layout/todays-scheduled/': {
      id: '/dashboard/_layout/todays-scheduled/'
      path: '/todays-scheduled'
      fullPath: '/dashboard/todays-scheduled'
      preLoaderRoute: typeof DashboardLayoutTodaysScheduledIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/': {
      id: '/dashboard/_layout/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/report/': {
      id: '/dashboard/_layout/report/'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardLayoutReportIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/published/': {
      id: '/dashboard/_layout/published/'
      path: '/published'
      fullPath: '/dashboard/published'
      preLoaderRoute: typeof DashboardLayoutPublishedIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/publications/': {
      id: '/dashboard/_layout/publications/'
      path: '/publications'
      fullPath: '/dashboard/publications'
      preLoaderRoute: typeof DashboardLayoutPublicationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/pricing-config/': {
      id: '/dashboard/_layout/pricing-config/'
      path: '/pricing-config'
      fullPath: '/dashboard/pricing-config'
      preLoaderRoute: typeof DashboardLayoutPricingConfigIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/packages/': {
      id: '/dashboard/_layout/packages/'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardLayoutPackagesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/inbox/': {
      id: '/dashboard/_layout/inbox/'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardLayoutInboxIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/drivers/': {
      id: '/dashboard/_layout/drivers/'
      path: '/drivers'
      fullPath: '/dashboard/drivers'
      preLoaderRoute: typeof DashboardLayoutDriversIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/cars/': {
      id: '/dashboard/_layout/cars/'
      path: '/cars'
      fullPath: '/dashboard/cars'
      preLoaderRoute: typeof DashboardLayoutCarsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/bookmarks/': {
      id: '/dashboard/_layout/bookmarks/'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardLayoutBookmarksIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/bookings/': {
      id: '/dashboard/_layout/bookings/'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardLayoutBookingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/board/': {
      id: '/dashboard/_layout/board/'
      path: '/board'
      fullPath: '/dashboard/board'
      preLoaderRoute: typeof DashboardLayoutBoardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/analytics/': {
      id: '/dashboard/_layout/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardLayoutAnalyticsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/admin-testing/': {
      id: '/dashboard/_layout/admin-testing/'
      path: '/admin-testing'
      fullPath: '/dashboard/admin-testing'
      preLoaderRoute: typeof DashboardLayoutAdminTestingIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/drivers/onboarding': {
      id: '/dashboard/_layout/drivers/onboarding'
      path: '/drivers/onboarding'
      fullPath: '/dashboard/drivers/onboarding'
      preLoaderRoute: typeof DashboardLayoutDriversOnboardingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/cars/add-car': {
      id: '/dashboard/_layout/cars/add-car'
      path: '/cars/add-car'
      fullPath: '/dashboard/cars/add-car'
      preLoaderRoute: typeof DashboardLayoutCarsAddCarRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/customer/_layout/book-service/$serviceId': {
      id: '/customer/_layout/book-service/$serviceId'
      path: '/book-service/$serviceId'
      fullPath: '/customer/book-service/$serviceId'
      preLoaderRoute: typeof CustomerLayoutBookServiceServiceIdRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/account/settings': {
      id: '/customer/_layout/account/settings'
      path: '/account/settings'
      fullPath: '/customer/account/settings'
      preLoaderRoute: typeof CustomerLayoutAccountSettingsRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutUsRoute: typeof MarketingAboutUsRoute
  MarketingBookingRoute: typeof MarketingBookingRoute
  MarketingContactUsRoute: typeof MarketingContactUsRoute
  MarketingFaqsRoute: typeof MarketingFaqsRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingServicesRoute: typeof MarketingServicesRoute
  MarketingTermsAndConditionsRoute: typeof MarketingTermsAndConditionsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutUsRoute: MarketingAboutUsRoute,
  MarketingBookingRoute: MarketingBookingRoute,
  MarketingContactUsRoute: MarketingContactUsRoute,
  MarketingFaqsRoute: MarketingFaqsRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingServicesRoute: MarketingServicesRoute,
  MarketingTermsAndConditionsRoute: MarketingTermsAndConditionsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface CustomerLayoutRouteChildren {
  CustomerLayoutBookingsRoute: typeof CustomerLayoutBookingsRoute
  CustomerLayoutInstantQuoteRoute: typeof CustomerLayoutInstantQuoteRoute
  CustomerLayoutProfileRoute: typeof CustomerLayoutProfileRoute
  CustomerLayoutServicesRoute: typeof CustomerLayoutServicesRoute
  CustomerLayoutIndexRoute: typeof CustomerLayoutIndexRoute
  CustomerLayoutAccountSettingsRoute: typeof CustomerLayoutAccountSettingsRoute
  CustomerLayoutBookServiceServiceIdRoute: typeof CustomerLayoutBookServiceServiceIdRoute
}

const CustomerLayoutRouteChildren: CustomerLayoutRouteChildren = {
  CustomerLayoutBookingsRoute: CustomerLayoutBookingsRoute,
  CustomerLayoutInstantQuoteRoute: CustomerLayoutInstantQuoteRoute,
  CustomerLayoutProfileRoute: CustomerLayoutProfileRoute,
  CustomerLayoutServicesRoute: CustomerLayoutServicesRoute,
  CustomerLayoutIndexRoute: CustomerLayoutIndexRoute,
  CustomerLayoutAccountSettingsRoute: CustomerLayoutAccountSettingsRoute,
  CustomerLayoutBookServiceServiceIdRoute:
    CustomerLayoutBookServiceServiceIdRoute,
}

const CustomerLayoutRouteWithChildren = CustomerLayoutRoute._addFileChildren(
  CustomerLayoutRouteChildren,
)

interface CustomerRouteChildren {
  CustomerLayoutRoute: typeof CustomerLayoutRouteWithChildren
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerLayoutRoute: CustomerLayoutRouteWithChildren,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutCarsAddCarRoute: typeof DashboardLayoutCarsAddCarRoute
  DashboardLayoutDriversOnboardingRoute: typeof DashboardLayoutDriversOnboardingRoute
  DashboardLayoutAdminTestingIndexRoute: typeof DashboardLayoutAdminTestingIndexRoute
  DashboardLayoutAnalyticsIndexRoute: typeof DashboardLayoutAnalyticsIndexRoute
  DashboardLayoutBoardIndexRoute: typeof DashboardLayoutBoardIndexRoute
  DashboardLayoutBookingsIndexRoute: typeof DashboardLayoutBookingsIndexRoute
  DashboardLayoutBookmarksIndexRoute: typeof DashboardLayoutBookmarksIndexRoute
  DashboardLayoutCarsIndexRoute: typeof DashboardLayoutCarsIndexRoute
  DashboardLayoutDriversIndexRoute: typeof DashboardLayoutDriversIndexRoute
  DashboardLayoutInboxIndexRoute: typeof DashboardLayoutInboxIndexRoute
  DashboardLayoutPackagesIndexRoute: typeof DashboardLayoutPackagesIndexRoute
  DashboardLayoutPricingConfigIndexRoute: typeof DashboardLayoutPricingConfigIndexRoute
  DashboardLayoutPublicationsIndexRoute: typeof DashboardLayoutPublicationsIndexRoute
  DashboardLayoutPublishedIndexRoute: typeof DashboardLayoutPublishedIndexRoute
  DashboardLayoutReportIndexRoute: typeof DashboardLayoutReportIndexRoute
  DashboardLayoutSettingsIndexRoute: typeof DashboardLayoutSettingsIndexRoute
  DashboardLayoutTodaysScheduledIndexRoute: typeof DashboardLayoutTodaysScheduledIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutCarsAddCarRoute: DashboardLayoutCarsAddCarRoute,
  DashboardLayoutDriversOnboardingRoute: DashboardLayoutDriversOnboardingRoute,
  DashboardLayoutAdminTestingIndexRoute: DashboardLayoutAdminTestingIndexRoute,
  DashboardLayoutAnalyticsIndexRoute: DashboardLayoutAnalyticsIndexRoute,
  DashboardLayoutBoardIndexRoute: DashboardLayoutBoardIndexRoute,
  DashboardLayoutBookingsIndexRoute: DashboardLayoutBookingsIndexRoute,
  DashboardLayoutBookmarksIndexRoute: DashboardLayoutBookmarksIndexRoute,
  DashboardLayoutCarsIndexRoute: DashboardLayoutCarsIndexRoute,
  DashboardLayoutDriversIndexRoute: DashboardLayoutDriversIndexRoute,
  DashboardLayoutInboxIndexRoute: DashboardLayoutInboxIndexRoute,
  DashboardLayoutPackagesIndexRoute: DashboardLayoutPackagesIndexRoute,
  DashboardLayoutPricingConfigIndexRoute:
    DashboardLayoutPricingConfigIndexRoute,
  DashboardLayoutPublicationsIndexRoute: DashboardLayoutPublicationsIndexRoute,
  DashboardLayoutPublishedIndexRoute: DashboardLayoutPublishedIndexRoute,
  DashboardLayoutReportIndexRoute: DashboardLayoutReportIndexRoute,
  DashboardLayoutSettingsIndexRoute: DashboardLayoutSettingsIndexRoute,
  DashboardLayoutTodaysScheduledIndexRoute:
    DashboardLayoutTodaysScheduledIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DriverLayoutRouteChildren {
  DriverLayoutOnboardingRoute: typeof DriverLayoutOnboardingRoute
  DriverLayoutProfileRoute: typeof DriverLayoutProfileRoute
  DriverLayoutSettingsRoute: typeof DriverLayoutSettingsRoute
  DriverLayoutTripsRoute: typeof DriverLayoutTripsRoute
  DriverLayoutIndexRoute: typeof DriverLayoutIndexRoute
}

const DriverLayoutRouteChildren: DriverLayoutRouteChildren = {
  DriverLayoutOnboardingRoute: DriverLayoutOnboardingRoute,
  DriverLayoutProfileRoute: DriverLayoutProfileRoute,
  DriverLayoutSettingsRoute: DriverLayoutSettingsRoute,
  DriverLayoutTripsRoute: DriverLayoutTripsRoute,
  DriverLayoutIndexRoute: DriverLayoutIndexRoute,
}

const DriverLayoutRouteWithChildren = DriverLayoutRoute._addFileChildren(
  DriverLayoutRouteChildren,
)

interface DriverRouteChildren {
  DriverLayoutRoute: typeof DriverLayoutRouteWithChildren
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverLayoutRoute: DriverLayoutRouteWithChildren,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CustomerRoute: CustomerRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
