import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
} from "@workspace/ui/components/dialog";
import { useModal } from "@/hooks/use-modal";
import { generatePricingConfigName } from "../_utils/auto-naming";
import { PricingConfigForm } from "./pricing-config-form";

export function CreatePricingConfigDialog() {
	const { isModalOpen, modalState, closeModal } = useModal();

	const open = isModalOpen("create-pricing-config");
	const modalData = modalState.data as
		| {
				carId?: string;
				carName?: string;
				carBrand?: string;
				carModel?: string;
				fromPublicationManagement?: boolean;
		  }
		| undefined;

	const handleSuccess = () => {
		closeModal();
	};

	// Generate auto-complete name if opened from publication management
	const autoGeneratedName =
		modalData?.fromPublicationManagement && modalData.carName
			? generatePricingConfigName(
					modalData.carName,
					modalData.carBrand,
					modalData.carModel,
				)
			: undefined;

	const initialData = modalData?.carId
		? {
				carId: modalData.carId,
				...(autoGeneratedName && { name: autoGeneratedName }),
			}
		: undefined;

	return (
		<Dialog open={open} onOpenChange={(open) => !open && closeModal()}>
			<DialogContent
				className="flex h-[85vh] flex-col p-0 sm:max-w-4xl"
				showCloseButton={false}
			>
				{/* Sticky Header */}
				<DialogHeader className="sticky top-0 z-10 flex-shrink-0 border-b bg-background/95 px-6 pt-6 pb-4 backdrop-blur supports-[backdrop-filter]:bg-background/60">
					<DialogTitle>
						Create Pricing Configuration
						{modalData?.carName && ` for ${modalData.carName}`}
					</DialogTitle>
					<DialogDescription>
						Set up pricing rules for this vehicle. All fields are required for
						publication.
						{autoGeneratedName && (
							<span className="mt-1 block text-muted-foreground text-sm">
								Configuration name auto-generated based on vehicle details.
							</span>
						)}
					</DialogDescription>
				</DialogHeader>

				{/* Scrollable Content */}
				<div className="min-h-0 flex-1">
					<PricingConfigForm
						initialData={initialData}
						onSuccess={handleSuccess}
						onCancel={closeModal}
						mode="create"
						contextData={{
							carName: modalData?.carName,
							carBrand: modalData?.carBrand,
							carModel: modalData?.carModel,
							fromPublicationManagement: modalData?.fromPublicationManagement,
							autoGeneratedName: autoGeneratedName,
						}}
					/>
				</div>
			</DialogContent>
		</Dialog>
	);
}
