import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
} from "@workspace/ui/components/dialog";
import { useModal } from "@/hooks/use-modal";
import { PricingConfigForm } from "./pricing-config-form";
import { generatePricingConfigName } from "../_utils/auto-naming";

export function CreatePricingConfigDialog() {
	const { isModalOpen, modalState, closeModal } = useModal();
	
	const open = isModalOpen("create-pricing-config");
	const modalData = modalState.data as { 
		carId?: string; 
		carName?: string;
		carBrand?: string;
		carModel?: string;
		fromPublicationManagement?: boolean;
	} | undefined;

	const handleSuccess = () => {
		closeModal();
	};

	// Generate auto-complete name if opened from publication management
	const autoGeneratedName = modalData?.fromPublicationManagement && modalData.carName
		? generatePricingConfigName(modalData.carName, modalData.carBrand, modalData.carModel)
		: undefined;

	const initialData = modalData?.carId ? { 
		carId: modalData.carId,
		...(autoGeneratedName && { name: autoGeneratedName })
	} : undefined;

	return (
		<Dialog open={open} onOpenChange={(open) => !open && closeModal()}>
			<DialogContent className="sm:max-w-4xl h-[85vh] flex flex-col p-0" showCloseButton={false}>
				{/* Sticky Header */}
				<DialogHeader className="flex-shrink-0 sticky top-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 border-b pt-6 px-6 pb-4">
					<DialogTitle>
						Create Pricing Configuration
						{modalData?.carName && ` for ${modalData.carName}`}
					</DialogTitle>
					<DialogDescription>
						Set up pricing rules for this vehicle. All fields are required for publication.
						{autoGeneratedName && (
							<span className="block mt-1 text-sm text-muted-foreground">
								Configuration name auto-generated based on vehicle details.
							</span>
						)}
					</DialogDescription>
				</DialogHeader>
				
				{/* Scrollable Content */}
				<div className="flex-1 min-h-0">
					<PricingConfigForm
						initialData={initialData}
						onSuccess={handleSuccess}
						onCancel={closeModal}
						mode="create"
						contextData={{
							carName: modalData?.carName,
							carBrand: modalData?.carBrand,
							carModel: modalData?.carModel,
							fromPublicationManagement: modalData?.fromPublicationManagement,
							autoGeneratedName: autoGeneratedName,
						}}
					/>
				</div>
			</DialogContent>
		</Dialog>
	);
}