import { zodResolver } from "@hookform/resolvers/zod";
import { Link } from "@tanstack/react-router";
import { Button } from "@workspace/ui/components/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@workspace/ui/components/card";
import {
	Form,
	FormControl,
	FormDescription,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@workspace/ui/components/form";
import { Input } from "@workspace/ui/components/input";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@workspace/ui/components/select";
import { Separator } from "@workspace/ui/components/separator";
import { Switch } from "@workspace/ui/components/switch";
import {
	ArrowRight,
	Calendar,
	Car,
	Clock,
	DollarSign,
	Loader2,
	Plus,
} from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useCreatePricingConfigMutation } from "../_hooks/query/use-create-pricing-config-mutation";
import { useGetCarsWithoutPricingQuery } from "../_hooks/query/use-get-cars-without-pricing-query";
import { useUpdatePricingConfigMutation } from "../_hooks/query/use-update-pricing-config-mutation";

const pricingConfigSchema = z.object({
	name: z
		.string()
		.min(1, "Please enter a configuration name")
		.max(100, "Name too long"),
	carId: z
		.string()
		.min(1, "Please select a car for this pricing configuration"),
	firstKmRate: z
		.number({ message: "Please enter the first KM rate" })
		.min(0.01, "First KM rate must be greater than 0"),
	firstKmLimit: z
		.union([
			z
				.number({ message: "First KM limit must be a valid number" })
				.min(1, "First KM limit must be at least 1"),
			z.undefined(),
		])
		.optional(),
	pricePerKm: z
		.union([
			z
				.number({ message: "Additional KM rate must be a valid number" })
				.min(0.01, "Additional KM rate must be greater than 0"),
			z.undefined(),
		])
		.optional(),
	/** Optional: used for instant quote / hourly package bookings for this vehicle */
	hourlyRate: z
		.union([
			z
				.number({ message: "Hourly rate must be a valid number" })
				.min(0.01, "Hourly rate must be greater than 0"),
			z.undefined(),
		])
		.optional(),
	isActive: z.boolean().default(true),
});

type PricingConfigForm = z.infer<typeof pricingConfigSchema>;

type PricingConfigFormProps = {
	initialData?: any;
	onSuccess?: () => void;
	onCancel?: () => void;
	mode?: "create" | "edit";
	// Publication management enhancements
	contextData?: {
		carName?: string;
		carBrand?: string;
		carModel?: string;
		fromPublicationManagement?: boolean;
		autoGeneratedName?: string;
	};
};

export function PricingConfigForm({
	initialData,
	onSuccess,
	onCancel,
	mode = "create",
	contextData,
}: PricingConfigFormProps) {
	const [isSubmitting, setIsSubmitting] = useState(false);
	const createMutation = useCreatePricingConfigMutation();
	const updateMutation = useUpdatePricingConfigMutation();
	const {
		data: cars,
		isLoading: carsLoading,
		error: carsError,
	} = useGetCarsWithoutPricingQuery();

	const form = useForm({
		resolver: zodResolver(pricingConfigSchema),
		defaultValues: {
			name: initialData?.name || contextData?.autoGeneratedName || "",
			carId: initialData?.carId || "",
			firstKmRate: initialData?.firstKmRate || undefined,
			firstKmLimit: initialData?.firstKmLimit || undefined,
			pricePerKm: initialData?.pricePerKm || undefined,
			hourlyRate: initialData?.hourlyRate ?? undefined,
			isActive: initialData?.isActive ?? true,
		},
	});

	// Debug logging
	console.log("Cars query result:", {
		cars,
		isLoading: carsLoading,
		error: carsError,
	});

	// Auto-generate name based on selected car
	const selectedCarId = form.watch("carId");
	const currentName = form.watch("name");

	useEffect(() => {
		// Only auto-generate name if creating a new config (not editing) and carId is selected
		if (mode === "create" && selectedCarId && cars) {
			const selectedCar = cars.find((car) => car.id === selectedCarId);
			if (selectedCar) {
				const autoGeneratedName = `${selectedCar.name} Pricing Config`;
				// Only update if current name is empty or was previously auto-generated
				if (!currentName || currentName.includes("Pricing Config")) {
					form.setValue("name", autoGeneratedName);
				}
			}
		}
	}, [selectedCarId, cars, mode, form, currentName]);

	const onSubmit = async (data: PricingConfigForm) => {
		setIsSubmitting(true);
		try {
			// Only send columns that exist on pricing_configs (omit isActive — not a DB column)
			const firstKmLimit = data.firstKmLimit ?? 10;
			const pricePerKm = data.pricePerKm ?? 4.85;
			const hourlyRate =
				typeof data.hourlyRate === "number" && !Number.isNaN(data.hourlyRate)
					? data.hourlyRate
					: null;

			const resolvedCarId =
				data.carId?.trim() || initialData?.carId?.trim() || undefined;

			if (mode === "edit" && initialData?.id) {
				await updateMutation.mutateAsync({
					id: initialData.id,
					name: data.name,
					firstKmRate: data.firstKmRate,
					firstKmLimit,
					pricePerKm,
					hourlyRate,
					...(resolvedCarId ? { carId: resolvedCarId } : {}),
				});
			} else {
				await createMutation.mutateAsync({
					name: data.name,
					carId: data.carId,
					firstKmRate: data.firstKmRate,
					firstKmLimit,
					pricePerKm,
					hourlyRate,
				});
			}
			form.reset();
			onSuccess?.();
		} catch (error) {
			console.error("Failed to save pricing configuration:", error);
		} finally {
			setIsSubmitting(false);
		}
	};

	return (
		<Form {...(form as any)}>
			<div className="flex h-full flex-col">
				<div className="flex-1 overflow-y-auto px-6 py-4">
					<div className="space-y-6">
						<div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
							{/* Left Column */}
							<div className="space-y-6">
								{/* Basic Configuration */}
								<Card>
									<CardHeader>
										<CardTitle className="flex items-center gap-2">
											<DollarSign className="h-5 w-5" />
											Pricing Configuration
										</CardTitle>
										<CardDescription>
											Simplified pricing structure with first 10KM rate and
											additional KM rate
										</CardDescription>
									</CardHeader>
									<CardContent className="space-y-4">
										{/* Car Selection - Show selector only when creating new config */}
										{contextData?.fromPublicationManagement ? (
											<div className="space-y-2">
												<FormLabel>Selected Car</FormLabel>
												<div className="flex items-center gap-2 rounded-md border bg-muted/50 p-3">
													<Car className="h-4 w-4" />
													<span className="font-medium">
														{contextData.carName}
													</span>
													{contextData.carBrand && contextData.carModel && (
														<span className="text-muted-foreground">
															({contextData.carBrand} {contextData.carModel})
														</span>
													)}
												</div>
												<p className="text-muted-foreground text-sm">
													This pricing configuration will be applied to the
													selected car from Publication Management.
												</p>
											</div>
										) : mode === "edit" ? (
											<div className="space-y-2">
												<FormLabel>Selected Car</FormLabel>
												<div className="flex items-center gap-2 rounded-md border bg-muted/50 p-3">
													<Car className="h-4 w-4" />
													<span className="font-medium">
														{initialData?.car?.name || "Selected Car"}
													</span>
													{initialData?.car?.licensePlate && (
														<span className="text-muted-foreground">
															({initialData.car.licensePlate})
														</span>
													)}
												</div>
												<p className="text-muted-foreground text-sm">
													Car selection cannot be changed when editing existing
													pricing configurations.
												</p>
											</div>
										) : (
											<>
												{cars?.length ? (
													<FormField
														control={form.control as any}
														name="carId"
														render={({ field }) => (
															<FormItem>
																<FormLabel>Select Car</FormLabel>
																<Select
																	onValueChange={field.onChange}
																	value={field.value || ""}
																>
																	<FormControl>
																		<SelectTrigger className="bg-white">
																			<SelectValue placeholder="Choose a car for this pricing configuration" />
																		</SelectTrigger>
																	</FormControl>
																	<SelectContent>
																		{carsLoading ? (
																			<SelectItem value="loading" disabled>
																				Loading cars...
																			</SelectItem>
																		) : carsError ? (
																			<SelectItem value="error" disabled>
																				Error loading cars. Please refresh the
																				page.
																			</SelectItem>
																		) : (
																			cars.map((car) => (
																				<SelectItem
																					key={car.id}
																					value={car.id}
																					className="bg-white"
																				>
																					<div className="flex items-center gap-2">
																						<Car className="h-4 w-4" />
																						<span>{car.name}</span>
																						<span className="text-muted-foreground">
																							({car.licensePlate})
																						</span>
																					</div>
																				</SelectItem>
																			))
																		)}
																	</SelectContent>
																</Select>
																<FormDescription>
																	Each car can have its own pricing
																	configuration for different luxury tiers.
																</FormDescription>
																<FormMessage />
															</FormItem>
														)}
													/>
												) : carsLoading ? (
													<div className="space-y-2">
														<FormLabel>Select Car</FormLabel>
														<div className="flex items-center gap-2 rounded-md border p-3">
															<Loader2 className="h-4 w-4 animate-spin" />
															<span className="text-muted-foreground">
																Loading available cars...
															</span>
														</div>
													</div>
												) : carsError ? (
													<div className="space-y-2">
														<FormLabel>Select Car</FormLabel>
														<div className="rounded-lg border border-red-200 bg-red-50 p-4">
															<div className="mb-2 flex items-center gap-2 text-red-800">
																<Car className="h-4 w-4" />
																<span className="font-medium">
																	Error Loading Cars
																</span>
															</div>
															<p className="mb-3 text-red-700 text-sm">
																Unable to load available cars. Please refresh
																the page and try again.
															</p>
															<Button
																type="button"
																variant="outline"
																size="sm"
																onClick={() => window.location.reload()}
																className="border-red-200 text-red-800 hover:bg-red-100"
															>
																Refresh Page
															</Button>
														</div>
													</div>
												) : (
													<div className="space-y-2">
														<FormLabel>Select Car</FormLabel>
														<div className="rounded-lg border border-primary/20 bg-primary/5 p-6">
															<div className="space-y-4 text-center">
																<div className="flex justify-center">
																	<div className="rounded-full bg-primary/10 p-3">
																		<Car className="h-8 w-8 text-primary" />
																	</div>
																</div>
																<div>
																	<h3 className="mb-2 font-medium text-foreground text-lg">
																		No Cars Available
																	</h3>
																	<p className="mb-4 text-muted-foreground text-sm">
																		All cars already have pricing
																		configurations. You need to add a new car to
																		create additional pricing configurations.
																	</p>
																</div>
																<Link to="/admin/dashboard/cars/add-car">
																	<Button className="bg-primary text-primary-foreground hover:bg-primary/90">
																		<Plus className="mr-2 h-4 w-4" />
																		Add New Car
																		<ArrowRight className="ml-2 h-4 w-4" />
																	</Button>
																</Link>
																<p className="text-muted-foreground text-xs">
																	After adding a car, return here to create its
																	pricing configuration.
																</p>
															</div>
														</div>
													</div>
												)}
											</>
										)}

										<FormField
											control={form.control as any}
											name="name"
											render={({ field }) => (
												<FormItem>
													<FormLabel>Configuration Name</FormLabel>
													<FormControl>
														<Input
															placeholder="e.g., Mercedes S-Class Pricing Config"
															{...field}
															className="bg-white"
														/>
													</FormControl>
													<FormDescription className="text-muted-foreground text-sm">
														Auto-generated based on selected car. You can modify
														it if needed.
													</FormDescription>
													<FormMessage />
												</FormItem>
											)}
										/>

										<div className="grid grid-cols-1 gap-4">
											<FormField
												control={form.control as any}
												name="firstKmRate"
												render={({ field }) => (
													<FormItem>
														<FormLabel>First KM Rate (AUD)</FormLabel>
														<FormControl>
															<Input
																type="number"
																step="0.01"
																min="0"
																placeholder="e.g. 200"
																className="bg-white"
																{...field}
																value={field.value ?? ""}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === "") {
																		field.onChange(undefined);
																	} else {
																		const numValue = Number.parseFloat(value);
																		field.onChange(
																			isNaN(numValue) ? undefined : numValue,
																		);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>
															Rate per kilometer for the first KM tier
														</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>

											<FormField
												control={form.control as any}
												name="firstKmLimit"
												render={({ field }) => (
													<FormItem>
														<FormLabel>First KM Limit</FormLabel>
														<FormControl>
															<Input
																type="number"
																min="1"
																step="1"
																placeholder="Default: 10"
																className="bg-white"
																{...field}
																value={
																	field.value === undefined ? "" : field.value
																}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === "") {
																		field.onChange(undefined);
																	} else {
																		const numValue = Number.parseInt(value);
																		field.onChange(
																			isNaN(numValue) ? undefined : numValue,
																		);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>
															How many kilometers at the first KM rate (defaults
															to 10 if left empty)
														</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>

											<FormField
												control={form.control as any}
												name="pricePerKm"
												render={({ field }) => (
													<FormItem>
														<FormLabel>Additional KM Rate (AUD)</FormLabel>
														<FormControl>
															<Input
																type="number"
																step="0.01"
																min="0"
																placeholder="Default: 4.85"
																className="bg-white"
																{...field}
																value={
																	field.value === undefined ? "" : field.value
																}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === "") {
																		field.onChange(undefined);
																	} else {
																		const numValue = Number.parseFloat(value);
																		field.onChange(
																			isNaN(numValue) ? undefined : numValue,
																		);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>
															Rate charged per kilometer above the first KM
															limit (defaults to $4.85 if left empty)
														</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>

											<FormField
												control={form.control as any}
												name="hourlyRate"
												render={({ field }) => (
													<FormItem>
														<FormLabel className="flex items-center gap-2">
															<Clock className="h-4 w-4" />
															Hourly rate (AUD, optional)
														</FormLabel>
														<FormControl>
															<Input
																type="number"
																step="0.01"
																min="0"
																placeholder="e.g. 120 — for instant quote hourly"
																className="bg-white"
																{...field}
																value={
																	field.value === undefined ? "" : field.value
																}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === "") {
																		field.onChange(undefined);
																	} else {
																		const numValue = Number.parseFloat(value);
																		field.onChange(
																			isNaN(numValue) ? undefined : numValue,
																		);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>
															When set, this vehicle appears in the home instant
															quote calculator for hourly bookings at this rate.
														</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>
										</div>

										<div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
											<div className="flex items-start gap-3">
												<div className="rounded-full bg-blue-100 p-1">
													<DollarSign className="h-4 w-4 text-blue-600" />
												</div>
												<div className="text-blue-800 text-sm">
													<p className="mb-1 font-medium">
														How flexible pricing works:
													</p>
													<ul className="space-y-1 text-blue-700">
														<li>
															• First tier: Flat rate for distances up to the KM
															limit
														</li>
														<li>
															• Additional tier: Remaining KM × Additional KM
															Rate
														</li>
														<li>
															• Example: 15KM trip with 10KM limit = $200 + (5 ×
															$4.85)
														</li>
													</ul>
												</div>
											</div>
										</div>
									</CardContent>
								</Card>
							</div>

							{/* Right Column - Configuration Status */}
							<div className="space-y-6">
								{/* Configuration Status */}
								<Card>
									<CardHeader>
										<CardTitle>Configuration Status</CardTitle>
										<CardDescription>
											Enable or disable this pricing configuration
										</CardDescription>
									</CardHeader>
									<CardContent>
										<FormField
											control={form.control as any}
											name="isActive"
											render={({ field }) => (
												<FormItem className="flex flex-row items-center justify-between rounded-lg border bg-white p-3">
													<div className="space-y-0.5">
														<FormLabel>Active Configuration</FormLabel>
														<FormDescription>
															Enable this pricing configuration for new bookings
														</FormDescription>
													</div>
													<FormControl>
														<Switch
															checked={field.value}
															onCheckedChange={field.onChange}
														/>
													</FormControl>
												</FormItem>
											)}
										/>
									</CardContent>
								</Card>

								{/* Pricing Preview */}
								<Card>
									<CardHeader>
										<CardTitle>Pricing Preview</CardTitle>
										<CardDescription>
											How the pricing calculation will work
										</CardDescription>
									</CardHeader>
									<CardContent>
										<div className="space-y-3 text-sm">
											<div className="flex justify-between">
												<span className="text-muted-foreground">
													First {form.watch("firstKmLimit") || 10} KM:
												</span>
												<span className="font-medium">
													${form.watch("firstKmRate") || 0} flat rate
												</span>
											</div>
											<div className="flex justify-between">
												<span className="text-muted-foreground">
													Additional KM:
												</span>
												<span className="font-medium">
													${form.watch("pricePerKm") || 4.85} per KM
												</span>
											</div>
											{form.watch("hourlyRate") != null &&
											(form.watch("hourlyRate") as number) > 0 ? (
												<div className="flex justify-between">
													<span className="text-muted-foreground">
														Hourly (instant quote):
													</span>
													<span className="font-medium">
														${Number(form.watch("hourlyRate")).toFixed(2)}
														/hr
													</span>
												</div>
											) : null}
											<div className="border-t pt-2">
												<div className="mb-1 text-muted-foreground text-xs">
													Example: 15KM trip
												</div>
												<div className="space-y-1 text-xs">
													<div>
														• First {form.watch("firstKmLimit") || 10}KM: $
														{form.watch("firstKmRate") || 0} (flat rate)
													</div>
													<div>
														• Additional 5KM: 5 × $
														{form.watch("pricePerKm") || 4.85} = $
														{(5 * (form.watch("pricePerKm") || 4.85)).toFixed(
															2,
														)}
													</div>
													<div className="border-t pt-1 font-medium">
														Total: $
														{(
															(form.watch("firstKmRate") || 0) +
															5 * (form.watch("pricePerKm") || 4.85)
														).toFixed(2)}
													</div>
												</div>
											</div>
										</div>
									</CardContent>
								</Card>
							</div>
						</div>
					</div>
				</div>

				{/* Sticky Footer */}
				<div className="flex-shrink-0 border-t bg-background/95 p-6 backdrop-blur supports-[backdrop-filter]:bg-background/60">
					<form onSubmit={form.handleSubmit(onSubmit)}>
						<div className="flex justify-end space-x-2">
							{onCancel && (
								<Button
									type="button"
									variant="outline"
									onClick={onCancel}
									disabled={isSubmitting}
									size="lg"
								>
									Cancel
								</Button>
							)}
							<Button
								type="submit"
								disabled={
									isSubmitting ||
									(!cars?.length &&
										mode === "create" &&
										!contextData?.fromPublicationManagement)
								}
								size="lg"
							>
								{isSubmitting && (
									<Loader2 className="mr-2 h-4 w-4 animate-spin" />
								)}
								{mode === "edit"
									? "Update Configuration"
									: "Create Configuration"}
							</Button>
						</div>
					</form>
				</div>
			</div>
		</Form>
	);
}
