import { Button } from "@workspace/ui/components/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage, FormDescription } from "@workspace/ui/components/form";
import { Input } from "@workspace/ui/components/input";
import { Switch } from "@workspace/ui/components/switch";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@workspace/ui/components/card";
import { Separator } from "@workspace/ui/components/separator";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@workspace/ui/components/select";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useState, useEffect } from "react";
import { useCreatePricingConfigMutation } from "../_hooks/query/use-create-pricing-config-mutation";
import { useUpdatePricingConfigMutation } from "../_hooks/query/use-update-pricing-config-mutation";
import { Loader2, DollarSign, Clock, Calendar, Car } from "lucide-react";
import { useGetCarsWithoutPricingQuery } from "../_hooks/query/use-get-cars-without-pricing-query";

const pricingConfigSchema = z.object({
	name: z.string().min(1, "Please enter a configuration name").max(100, "Name too long"),
	carId: z.string().min(1, "Please select a car for this pricing configuration"),
	firstKmRate: z.number({ 
		required_error: "Please enter the first KM rate",
		invalid_type_error: "First KM rate must be a valid number"
	}).min(0.01, "First KM rate must be greater than 0"),
	firstKmLimit: z.union([
		z.number({ invalid_type_error: "First KM limit must be a valid number" }).min(1, "First KM limit must be at least 1"),
		z.undefined()
	]).optional(),
	pricePerKm: z.union([
		z.number({ invalid_type_error: "Additional KM rate must be a valid number" }).min(0.01, "Additional KM rate must be greater than 0"),
		z.undefined()
	]).optional(),
	isActive: z.boolean().default(true),
});

type PricingConfigForm = z.infer<typeof pricingConfigSchema>;

type PricingConfigFormProps = {
	initialData?: any;
	onSuccess?: () => void;
	onCancel?: () => void;
	mode?: "create" | "edit";
	// Publication management enhancements
	contextData?: {
		carName?: string;
		carBrand?: string;
		carModel?: string;
		fromPublicationManagement?: boolean;
		autoGeneratedName?: string;
	};
};

export function PricingConfigForm({ initialData, onSuccess, onCancel, mode = "create", contextData }: PricingConfigFormProps) {
	const [isSubmitting, setIsSubmitting] = useState(false);
	const createMutation = useCreatePricingConfigMutation();
	const updateMutation = useUpdatePricingConfigMutation();
	const { data: cars, isLoading: carsLoading, error: carsError } = useGetCarsWithoutPricingQuery();

	const form = useForm({
		resolver: zodResolver(pricingConfigSchema),
		defaultValues: {
			name: initialData?.name || contextData?.autoGeneratedName || "",
			carId: initialData?.carId || "",
			firstKmRate: initialData?.firstKmRate || undefined,
			firstKmLimit: initialData?.firstKmLimit || undefined,
			pricePerKm: initialData?.pricePerKm || undefined,
			isActive: initialData?.isActive ?? true,
		},
	});

	// Debug logging
	console.log("Cars query result:", { cars, isLoading: carsLoading, error: carsError });

	// Auto-generate name based on selected car
	const selectedCarId = form.watch("carId");
	const currentName = form.watch("name");

	useEffect(() => {
		// Only auto-generate name if creating a new config (not editing) and carId is selected
		if (mode === "create" && selectedCarId && cars) {
			const selectedCar = cars.find(car => car.id === selectedCarId);
			if (selectedCar) {
				const autoGeneratedName = `${selectedCar.name} Pricing Config`;
				// Only update if current name is empty or was previously auto-generated
				if (!currentName || currentName.includes("Pricing Config")) {
					form.setValue("name", autoGeneratedName);
				}
			}
		}
	}, [selectedCarId, cars, mode, form, currentName]);

	const onSubmit = async (data: PricingConfigForm) => {
		setIsSubmitting(true);
		try {
			// Apply defaults for undefined values before submission
			const processedData = {
				...data,
				firstKmLimit: data.firstKmLimit ?? 10,
				pricePerKm: data.pricePerKm ?? 4.85,
			};

			if (mode === "edit" && initialData?.id) {
				await updateMutation.mutateAsync({ id: initialData.id, ...processedData });
			} else {
				await createMutation.mutateAsync(processedData);
			}
			form.reset();
			onSuccess?.();
		} catch (error) {
			console.error("Failed to save pricing configuration:", error);
		} finally {
			setIsSubmitting(false);
		}
	};

	return (
		<Form {...form as any}>
			<div className="flex flex-col h-full">
				<div className="flex-1 overflow-y-auto px-6 py-4">
					<div className="space-y-6">
						<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
							{/* Left Column */}
							<div className="space-y-6">
								{/* Basic Configuration */}
								<Card>
									<CardHeader>
										<CardTitle className="flex items-center gap-2">
											<DollarSign className="h-5 w-5" />
											Pricing Configuration
										</CardTitle>
										<CardDescription>Simplified pricing structure with first 10KM rate and additional KM rate</CardDescription>
									</CardHeader>
									<CardContent className="space-y-4">
										{/* Car Selection - Show selector only when creating new config */}
										{contextData?.fromPublicationManagement ? (
											<div className="space-y-2">
												<FormLabel>Selected Car</FormLabel>
												<div className="flex items-center gap-2 p-3 border rounded-md bg-muted/50">
													<Car className="h-4 w-4" />
													<span className="font-medium">{contextData.carName}</span>
													{contextData.carBrand && contextData.carModel && (
														<span className="text-muted-foreground">
															({contextData.carBrand} {contextData.carModel})
														</span>
													)}
												</div>
												<p className="text-sm text-muted-foreground">
													This pricing configuration will be applied to the selected car from Publication Management.
												</p>
											</div>
										) : mode === "edit" ? (
											<div className="space-y-2">
												<FormLabel>Selected Car</FormLabel>
												<div className="flex items-center gap-2 p-3 border rounded-md bg-muted/50">
													<Car className="h-4 w-4" />
													<span className="font-medium">{initialData?.car?.name || 'Selected Car'}</span>
													{initialData?.car?.licensePlate && (
														<span className="text-muted-foreground">
															({initialData.car.licensePlate})
														</span>
													)}
												</div>
												<p className="text-sm text-muted-foreground">
													Car selection cannot be changed when editing existing pricing configurations.
												</p>
											</div>
										) : (
											<FormField
												control={form.control as any}
												name="carId"
												render={({ field }) => (
													<FormItem>
														<FormLabel>Select Car</FormLabel>
														<Select onValueChange={field.onChange} value={field.value || ""}>
															<FormControl>
																<SelectTrigger className="bg-white">
																	<SelectValue placeholder="Choose a car for this pricing configuration" />
																</SelectTrigger>
															</FormControl>
															<SelectContent>
																{carsLoading ? (
																	<SelectItem value="loading" disabled>Loading cars...</SelectItem>
																) : carsError ? (
																	<SelectItem value="error" disabled>
																		Error loading cars. Please refresh the page.
																	</SelectItem>
																) : cars?.length ? (
																	cars.map((car) => (
																		<SelectItem key={car.id} value={car.id} className="bg-white">
																			<div className="flex items-center gap-2">
																				<Car className="h-4 w-4" />
																				<span>{car.name}</span>
																				<span className="text-muted-foreground">({car.licensePlate})</span>
																			</div>
																		</SelectItem>
																	))
																) : (
																	<SelectItem value="no-cars" disabled>No cars available</SelectItem>
																)}
															</SelectContent>
														</Select>
														<FormDescription>
															Each car can have its own pricing configuration for different luxury tiers.
														</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>
										)}

										<FormField
											control={form.control as any}
											name="name"
											render={({ field }) => (
												<FormItem>
													<FormLabel>Configuration Name</FormLabel>
													<FormControl>
														<Input placeholder="e.g., Mercedes S-Class Pricing Config" {...field} className="bg-white" />
													</FormControl>
													<FormDescription className="text-sm text-muted-foreground">
														Auto-generated based on selected car. You can modify it if needed.
													</FormDescription>
													<FormMessage />
												</FormItem>
											)}
										/>

										<div className="grid grid-cols-1 gap-4">
											<FormField
												control={form.control as any}
												name="firstKmRate"
												render={({ field }) => (
													<FormItem>
														<FormLabel>First KM Rate (AUD)</FormLabel>
														<FormControl>
															<Input
																type="number"
																step="0.01"
																min="0"
																placeholder="e.g. 200"
																className="bg-white"
																{...field}
																value={field.value ?? ''}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === '') {
																		field.onChange(undefined);
																	} else {
																		const numValue = parseFloat(value);
																		field.onChange(isNaN(numValue) ? undefined : numValue);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>Rate per kilometer for the first KM tier</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>

											<FormField
												control={form.control as any}
												name="firstKmLimit"
												render={({ field }) => (
													<FormItem>
														<FormLabel>First KM Limit</FormLabel>
														<FormControl>
															<Input
																type="number"
																min="1"
																step="1"
																placeholder="Default: 10"
																className="bg-white"
																{...field}
																value={field.value === undefined ? '' : field.value}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === '') {
																		field.onChange(undefined);
																	} else {
																		const numValue = parseInt(value);
																		field.onChange(isNaN(numValue) ? undefined : numValue);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>How many kilometers at the first KM rate (defaults to 10 if left empty)</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>

											<FormField
												control={form.control as any}
												name="pricePerKm"
												render={({ field }) => (
													<FormItem>
														<FormLabel>Additional KM Rate (AUD)</FormLabel>
														<FormControl>
															<Input
																type="number"
																step="0.01"
																min="0"
																placeholder="Default: 4.85"
																className="bg-white"
																{...field}
																value={field.value === undefined ? '' : field.value}
																onChange={(e) => {
																	const value = e.target.value;
																	if (value === '') {
																		field.onChange(undefined);
																	} else {
																		const numValue = parseFloat(value);
																		field.onChange(isNaN(numValue) ? undefined : numValue);
																	}
																}}
															/>
														</FormControl>
														<FormDescription>Rate charged per kilometer above the first KM limit (defaults to $4.85 if left empty)</FormDescription>
														<FormMessage />
													</FormItem>
												)}
											/>
										</div>

										<div className="rounded-lg border p-4 bg-blue-50 border-blue-200">
											<div className="flex items-start gap-3">
												<div className="rounded-full bg-blue-100 p-1">
													<DollarSign className="h-4 w-4 text-blue-600" />
												</div>
												<div className="text-sm text-blue-800">
													<p className="font-medium mb-1">How flexible pricing works:</p>
													<ul className="space-y-1 text-blue-700">
														<li>• First tier: Flat rate for distances up to the KM limit</li>
														<li>• Additional tier: Remaining KM × Additional KM Rate</li>
														<li>• Example: 15KM trip with 10KM limit = $200 + (5 × $4.85)</li>
													</ul>
												</div>
											</div>
										</div>
									</CardContent>
								</Card>
							</div>

							{/* Right Column - Configuration Status */}
							<div className="space-y-6">
								{/* Configuration Status */}
								<Card>
									<CardHeader>
										<CardTitle>Configuration Status</CardTitle>
										<CardDescription>Enable or disable this pricing configuration</CardDescription>
									</CardHeader>
									<CardContent>
										<FormField
											control={form.control as any}
											name="isActive"
											render={({ field }) => (
												<FormItem className="flex flex-row items-center justify-between rounded-lg border p-3 bg-white">
													<div className="space-y-0.5">
														<FormLabel>Active Configuration</FormLabel>
														<FormDescription>
															Enable this pricing configuration for new bookings
														</FormDescription>
													</div>
													<FormControl>
														<Switch
															checked={field.value}
															onCheckedChange={field.onChange}
														/>
													</FormControl>
												</FormItem>
											)}
										/>
									</CardContent>
								</Card>

								{/* Pricing Preview */}
								<Card>
									<CardHeader>
										<CardTitle>Pricing Preview</CardTitle>
										<CardDescription>How the pricing calculation will work</CardDescription>
									</CardHeader>
									<CardContent>
										<div className="space-y-3 text-sm">
											<div className="flex justify-between">
												<span className="text-muted-foreground">First {form.watch("firstKmLimit") || 10} KM:</span>
												<span className="font-medium">${form.watch("firstKmRate") || 0} flat rate</span>
											</div>
											<div className="flex justify-between">
												<span className="text-muted-foreground">Additional KM:</span>
												<span className="font-medium">${form.watch("pricePerKm") || 4.85} per KM</span>
											</div>
											<div className="pt-2 border-t">
												<div className="text-xs text-muted-foreground mb-1">Example: 15KM trip</div>
												<div className="text-xs space-y-1">
													<div>• First {form.watch("firstKmLimit") || 10}KM: ${form.watch("firstKmRate") || 0} (flat rate)</div>
													<div>• Additional 5KM: 5 × ${form.watch("pricePerKm") || 4.85} = ${(5 * (form.watch("pricePerKm") || 4.85)).toFixed(2)}</div>
													<div className="font-medium pt-1 border-t">Total: ${((form.watch("firstKmRate") || 0) + (5 * (form.watch("pricePerKm") || 4.85))).toFixed(2)}</div>
												</div>
											</div>
										</div>
									</CardContent>
								</Card>
							</div>
						</div>

					</div>
				</div>

				{/* Sticky Footer */}
				<div className="flex-shrink-0 border-t bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 p-6">
					<form onSubmit={form.handleSubmit(onSubmit)}>
						<div className="flex justify-end space-x-2">
							{onCancel && (
								<Button
									type="button"
									variant="outline"
									onClick={onCancel}
									disabled={isSubmitting}
									size="lg"
								>
									Cancel
								</Button>
							)}
							<Button
								type="submit"
								disabled={isSubmitting}
								size="lg"
							>
								{isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
								{mode === "edit" ? "Update Configuration" : "Create Configuration"}
							</Button>
						</div>
					</form>
				</div>
			</div>
		</Form>
	);
}
