import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
} from "@workspace/ui/components/dialog";
import { generatePricingConfigName } from "../_utils/auto-naming";
import { PricingConfigForm } from "./pricing-config-form";

interface UnifiedPricingConfigDialogProps {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	mode?: "create" | "edit";
	initialData?: any;

	// Context data for enhanced features
	contextData?: {
		carId?: string;
		carName?: string;
		carBrand?: string;
		carModel?: string;
		fromPublicationManagement?: boolean;
	};

	// Custom dialog props
	title?: string;
	description?: string;
}

export function UnifiedPricingConfigDialog({
	open,
	onOpenChange,
	mode = "create",
	initialData,
	contextData,
	title,
	description,
}: UnifiedPricingConfigDialogProps) {
	const handleSuccess = () => {
		onOpenChange(false);
	};

	// Generate auto-complete name if needed
	const autoGeneratedName =
		contextData?.fromPublicationManagement && contextData.carName
			? generatePricingConfigName(
					contextData.carName,
					contextData.carBrand,
					contextData.carModel,
				)
			: undefined;

	// Merge initial data with context
	const enhancedInitialData = {
		...initialData,
		...(contextData?.carId && { carId: contextData.carId }),
		...(autoGeneratedName && { name: autoGeneratedName }),
	};

	// Dynamic title and description
	const dialogTitle =
		title ||
		(mode === "create"
			? "Create Pricing Configuration"
			: "Edit Pricing Configuration");
	const dialogDescription =
		description ||
		(mode === "create"
			? "Set up pricing rules for this vehicle. All fields are required for publication."
			: "Update the pricing configuration settings.");

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent
				className="flex h-[85vh] flex-col p-0 sm:max-w-4xl"
				showCloseButton={false}
			>
				{/* Sticky Header */}
				<DialogHeader className="sticky top-0 z-10 flex-shrink-0 border-b bg-background/95 px-6 pt-6 pb-4 backdrop-blur supports-[backdrop-filter]:bg-background/60">
					<DialogTitle>
						{dialogTitle}
						{contextData?.carName && ` for ${contextData.carName}`}
					</DialogTitle>
					<DialogDescription>
						{dialogDescription}
						{autoGeneratedName && (
							<span className="mt-1 block text-muted-foreground text-sm">
								Configuration name auto-generated based on vehicle details.
							</span>
						)}
					</DialogDescription>
				</DialogHeader>

				{/* Scrollable Content */}
				<div className="min-h-0 flex-1">
					<PricingConfigForm
						initialData={enhancedInitialData}
						onSuccess={handleSuccess}
						onCancel={() => onOpenChange(false)}
						mode={mode}
						contextData={{
							...contextData,
							autoGeneratedName,
						}}
					/>
				</div>
			</DialogContent>
		</Dialog>
	);
}
